"use client";import{useState}from"react";
import StructuredData,{toolSchema,faqSchema,breadcrumbSchema}from"../../../components/StructuredData";
import Breadcrumb from"../../../components/Breadcrumb";import ShareButtons from"../../../components/ShareButtons";
import FAQSection from"../../../components/FAQSection";import RelatedTools from"../../../components/RelatedTools";import SEOContent from"../../../components/SEOContent";
const faqs=[
{question:"What is Markdown Editor?",answer:"A free tool for writing and editing Markdown text with live preview. Markdown is a simple formatting language that converts to HTML automatically."},
{question:"What is Markdown?",answer:"A lightweight markup language that lets you write formatted text (headers, lists, links, images) using simple symbols. Used on GitHub, Reddit, Notion, and more."},
{question:"Do I need to learn Markdown?",answer:"Very easy to learn in 5 minutes. ## for headers, **text** for bold, [text](url) for links, - for lists. Live preview shows results instantly."},
{question:"What's the difference between Markdown and HTML?",answer:"Markdown is simpler and faster to write. HTML is more powerful. Markdown converts to HTML automatically. Write in Markdown, get HTML ready."},
{question:"What are Markdown use cases?",answer:"GitHub README files, project documentation, blog writing, personal notes, technical docs, and educational content."},
{question:"Can I copy the output as HTML?",answer:"Yes, there's a 'Copy HTML' button that copies the formatted text as ready-to-use HTML."},
{question:"What features are supported?",answer:"H1-H6 headers, bold/italic, ordered/unordered lists, links, images, inline/block code, blockquotes, and horizontal rules."},
{question:"Is it completely free?",answer:"Yes, 100% free. No registration, no limits, no ads."},
{question:"Does it work on mobile?",answer:"Yes, fully responsive with side-by-side editor and preview."},
{question:"Can I download the result?",answer:"Yes, download as .md or .html file."},
];
const relatedTools=[{title:"JSON Formatter",icon:"📋",href:"/en/tools/json-formatter"},{title:"CSS Minifier",icon:"🎨",href:"/en/tools/css-minifier"},{title:"Hash Generator",icon:"#️⃣",href:"/en/tools/hash-generator"},{title:"Base64 Encoder",icon:"🔄",href:"/en/tools/base64-encoder"},{title:"SEO Audit",icon:"🔍",href:"/en/tools/seo-audit"},];
const seoContent=["Free Markdown Editor with live preview. Write in Markdown and see the formatted HTML result instantly. Perfect for developers, writers, and documentation.","Markdown is the most popular formatting language in tech. GitHub, Reddit, Notion, and Slack all support it. Learn it once, use it everywhere.","Supports all standard Markdown syntax: headers, lists, links, images, code, blockquotes. Instant live preview — every change shows immediately.","Direct HTML copy: write in Markdown, copy HTML for use on any website. Ideal for bloggers and content creators.","Tip: Write content in Markdown first, then copy HTML. Faster than writing HTML manually and fewer errors."];
function renderMarkdown(md:string):string{let h=md.replace(/^###### (.+)$/gm,"<h6>$1</h6>").replace(/^##### (.+)$/gm,"<h5>$1</h5>").replace(/^#### (.+)$/gm,"<h4>$1</h4>").replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h1>$1</h1>").replace(/\*\*\*(.+?)\*\*\*/g,"<strong><em>$1</em></strong>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/\*(.+?)\*/g,"<em>$1</em>").replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2" class="text-blue-600 hover:underline">$1</a>').replace(/!\[([^\]]*)\]\(([^)]+)\)/g,'<img src="$2" alt="$1" class="max-w-full rounded-lg" />').replace(/^---$/gm,"<hr class='my-4 border-gray-300' />").replace(/^> (.+)$/gm,'<blockquote class="border-l-4 border-blue-500 pl-4 text-gray-600 italic">$1</blockquote>').replace(/^[-*] (.+)$/gm,"<li>$1</li>").replace(/^\d+\. (.+)$/gm,"<li>$1</li>").replace(/\n\n/g,"</p><p>").replace(/\n/g,"<br />");h=h.replace(/((?:<li>.*?<\/li><br \/>?)+)/g,"<ul class='list-disc pl-5 my-2'>$1</ul>").replace(/<\/li><br \/>/g,"</li>");return"<p>"+h+"</p>";}
export default function MarkdownEditor(){const[input,setInput]=useState("# Hello!\nWrite **Markdown** here...");const[copied,setCopied]=useState(false);
const copyHTML=()=>{navigator.clipboard.writeText(renderMarkdown(input));setCopied(true);setTimeout(()=>setCopied(false),2000);};
const download=(ext:string,content:string)=>{const blob=new Blob([content],{type:"text/plain"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`document.${ext}`;a.click();URL.revokeObjectURL(url);};
return(<div className="max-w-[760px] mx-auto">
<StructuredData data={toolSchema("Markdown Editor","Write and edit Markdown with live preview","https://adwatak.cloud/en/tools/markdown-editor","en","Developer Tools")}/>
<StructuredData data={faqSchema(faqs)}/>
<StructuredData data={breadcrumbSchema([{name:"Home",url:"https://adwatak.cloud/en"},{name:"Developer Tools",url:"https://adwatak.cloud/en/tools/dev"},{name:"Markdown Editor",url:"https://adwatak.cloud/en/tools/markdown-editor"}])}/>
<Breadcrumb lang="en" category="Developer Tools" categorySlug="dev" toolName="Markdown Editor"/>
<div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6">
<h1 className="text-2xl font-extrabold mb-1">📝 Markdown Editor</h1><p className="text-sm text-gray-500 mb-6">Write Markdown and see the live preview</p>
<div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4"><textarea value={input} onChange={(e)=>setInput(e.target.value)} className="w-full h-[350px] p-4 border-2 border-gray-200 rounded-xl text-sm font-mono outline-none resize-y" placeholder="Write Markdown here..."/><div className="h-[350px] p-4 bg-white border-2 border-gray-200 rounded-xl overflow-y-auto text-sm leading-relaxed prose" dangerouslySetInnerHTML={{__html:renderMarkdown(input)}}/></div>
<div className="flex gap-3"><button onClick={copyHTML} className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-xl text-sm transition-all">{copied?"✅ Copied!":"📋 Copy HTML"}</button><button onClick={()=>download("md",input)} className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-xl text-sm transition-all">📥 Download .md</button><button onClick={()=>download("html",renderMarkdown(input))} className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-xl text-sm transition-all">📥 Download .html</button></div></div>
<SEOContent content={seoContent} lang="en"/><FAQSection faqs={faqs} lang="en"/><RelatedTools tools={relatedTools} lang="en"/><ShareButtons lang="en"/></div>);}
