"use client";import { useState } from "react";import StructuredData, { speakableSchema, toolSchema, faqSchema, breadcrumbSchema,howToSchema } from "../../../components/StructuredData";import Breadcrumb from "../../../components/Breadcrumb";import ShareButtons from "../../../components/ShareButtons";import FAQSection from "../../../components/FAQSection";import RelatedTools from "../../../components/RelatedTools";import SEOContent from "../../../components/SEOContent";const faqs = [
  { question: "Apa itu Detektor Konten AI?", answer: "Alat gratis yang menganalisis teks untuk menentukan apakah ditulis oleh manusia atau dihasilkan oleh AI. Menggunakan algoritma canggih untuk mendeteksi pola linguistik, pengulangan, dan struktur khas konten yang dihasilkan AI." },
  { question: "Seberapa akurat deteksi konten AI?", answer: "Akurasi tinggi melebihi 85% dalam kebanyakan kasus. Namun, tidak ada alat yang 100% akurat. Konten campuran (manusia + AI) lebih sulit diklasifikasikan. Gunakan ini sebagai referensi, bukan penilaian akhir." },
  { question: "Apakah ini berfungsi dengan bahasa Arab dan Inggris?", answer: "Ya, mendukung bahasa Arab dan Inggris dengan lancar, serta teks campuran bahasa. Bekerja dengan semua gaya penulisan dan dialek." },
  { question: "Bisakah deteksi AI dikelabui?", answer: "Konten AI yang banyak diedit lebih sulit dideteksi. Penulisan ulang oleh manusia mengurangi akurasi deteksi. Alat ini mendeteksi pola tersembunyi yang sulit dipalsukan oleh manusia." },
  { question: "Berapa panjang teks yang dibutuhkan?", answer: "Minimal 20 karakter. Teks yang lebih panjang memberikan akurasi lebih baik. Hasil terbaik dengan 200-2000 kata. Teks sangat pendek di bawah 50 kata kurang dapat diandalkan." },
  { question: "Apakah data saya aman dan pribadi?", answer: "100% pribadi. Teks Anda dikirim hanya untuk analisis dan tidak disimpan. Kami tidak menyimpan basis data konten yang dianalisis." },
  { question: "Apa saja tanda-tanda konten AI?", answer: "Pengulangan kata yang tidak alami, kalimat dengan panjang sedang yang seragam, kurangnya variasi kalimat, penggunaan kata transisi yang berlebihan, dan penjelasan berlebihan pada konsep sederhana." },
  { question: "Mengapa alat yang berbeda memberikan hasil yang berbeda?", answer: "Setiap alat menggunakan model AI dan metodologi yang berbeda. Praktik terbaik: bandingkan 2-3 alat. Alat kami menggunakan model canggih untuk analisis yang akurat." },
  { question: "Bisakah mendeteksi konten ChatGPT, Claude, dan Gemini?", answer: "Ya. Setiap model AI utama memiliki sidik jari linguistik yang unik. Alat ini dilatih untuk mengenali pola-pola tersebut di GPT-4, Claude, Gemini, dan lainnya." },
  { question: "Bagaimana saya bisa menggunakan ini untuk meningkatkan tulisan saya?", answer: "Tulis konten Anda sendiri terlebih dahulu. Uji. Skor rendah = bagus. Skor tinggi = tulis ulang dengan gaya Anda sendiri. Gunakan alat ini sebagai cermin untuk gaya penulisan Anda." },
  { question: "Apakah akademisi menggunakan detektor AI?", answer: "Ya, banyak universitas menggunakan deteksi AI untuk memverifikasi integritas akademik dalam makalah penelitian dan pengajuan mahasiswa. Ini membantu profesor mengevaluasi karya asli." },
  { question: "Apa perbedaan antara tulisan AI dan manusia?", answer: "Manusia menulis dengan variasi: kalimat pendek dan panjang, ekspresi emosional, bahasa sehari-hari. AI menulis secara seragam, sangat terorganisir, dan kurang spontan." }
];const relatedTools = [  { title: "Penghitung Kata", icon: "📝", href: "/id/tools/word-counter" },  { title: "Pembersih Teks", icon: "🧹", href: "/id/tools/text-cleaner" },  { title: "Pembanding Teks", icon: "⚖️", href: "/id/tools/text-compare" },  { title: "Pengubah Huruf Teks", icon: "🔤", href: "/id/tools/text-case" },  { title: "Pembuat QR", icon: "🔳", href: "/id/tools/qr-generator" },  { title: "Pembuat Kata Sandi", icon: "🔐", href: "/id/tools/password-generator" },];const seoContent = [
  "AI Content Detector adalah alat online gratis yang memindai teks dan memberi tahu Anda probabilitas teks tersebut dihasilkan oleh kecerdasan buatan. Cukup tempelkan teks Anda dan klik analisis. Alat ini mengirimkan teks Anda ke model AI khusus untuk analisis pola linguistik.",
  "Dengan ChatGPT, Claude, dan Gemini yang semakin umum, membedakan konten manusia dari AI menjadi lebih sulit dari sebelumnya. Alat kami membantu penulis, blogger, pendidik, dan siswa memverifikasi keaslian konten. Hasil ditampilkan sebagai persentase dengan penjelasan singkat.",
  "Untuk hasil terbaik: tempelkan teks lengkap minimal 100 kata. Teks yang sangat pendek dapat memberikan hasil yang tidak akurat. Uji berbagai teks untuk memahami cara kerja alat ini dan sesuaikan ekspektasi Anda.",
  "Akurasi analisis bergantung pada kualitas dan panjang teks. Teks lebih dari 500 kata mencapai akurasi hingga 90%. Konten AI yang ditulis ulang secara profesional dapat menurunkan tingkat deteksi, tetapi alat ini menangkap pola-pola halus.",
  "Penting: Tidak ada detektor AI yang 100% sempurna. Gunakan ini sebagai referensi yang membantu, bukan keputusan definitif. Gabungkan analisis otomatis dengan penilaian manusia untuk hasil terbaik."
];export default function Client() {  const [text, setText] = useState("");  const [result, setResult] = useState<{score: number; explanation: string} | null>(null);  const [loading, setLoading] = useState(false);  const [error, setError] = useState("");  const analyzeText = async () => {    if (text.trim().length < 20) {      setError("Silakan masukkan minimal 20 karakter");      return;    }    setError("");    setLoading(true);    setResult(null);    try {      const res = await fetch("/api/ai-content-detector", {        method: "POST",        headers: { "Content-Type": "application/json" },        body: JSON.stringify({ text: text.trim(), lang: "en" }),      });      if (!res.ok) {        const err = await res.json();        throw new Error(err.error || "Analysis failed");      }      const data = await res.json();      setResult(data);    } catch (e: any) {      setError(e.message || "An error occurred. Try again.");    } finally {      setLoading(false);    }  };  const getScoreColor = (score: number) => {    if (score < 30) return "text-green-600";    if (score < 60) return "text-yellow-600";    return "text-red-600";  };  const getScoreBg = (score: number) => {    if (score < 30) return "bg-green-50 border-green-200";    if (score < 60) return "bg-yellow-50 border-yellow-200";    return "bg-red-50 border-red-200";  };  const getScoreEmoji = (score: number) => {    if (score < 30) return "✅";    if (score < 60) return "⚠️";    return "🤖";  };  const getScoreLabel = (score: number) => {    if (score < 30) return "Likely Human Written";    if (score < 60) return "Possibly AI or Mixed";    return "Likely AI Generated";  };  return (    <div className="max-w-[760px] mx-auto">      <StructuredData data={toolSchema("Detektor Konten AI", "Detect if text is human-written or AI-generated", "https://adwatak.cloud/tools/ai-content-detector", "en", "Text Analysis")} />      <StructuredData data={faqSchema(faqs)} />      <StructuredData data={breadcrumbSchema([{name:"Home",url:"https://adwatak.cloud/en"},{name:"Alat Teks",url:"https://adwatak.cloud/id/category/text"},{name:"Detektor Konten AI",url:"https://adwatak.cloud/id/tools/ai-content-detector"}])} />{/* GEO: HowTo — step by step for AI engines */}
      <StructuredData data={howToSchema("Cara menggunakan alat ini", "Free online tool. Works directly in your browser. No registration required.", [{name:"Buka alat",text:"Arahkan ke halaman alat ini di Adawatak"},{name:"Masukkan data Anda",text:"Isi kolom yang diperlukan"},{name:"Dapatkan hasil",text:"Klik tombol hitung atau hasilkan"},{name:"Gunakan atau bagikan",text:"Salin, unduh, atau bagikan hasilnya"}],"kurang dari satu menit","id")} />
      {/* GEO: Speakable — AI/voice engines */}
      <StructuredData data={speakableSchema(["h1","h2","main"])} />
<Breadcrumb lang="en" category="Alat Teks" categorySlug="text" toolName="Detektor Konten AI" />      <div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6">        <h1 className="text-2xl font-extrabold mb-1">🤖 Detektor Konten AI</h1>        <p className="text-sm text-gray-500 mb-6">Deteksi apakah teks ditulis oleh manusia atau dihasilkan oleh AI</p>        <textarea value={text} onChange={(e) => setText(e.target.value)}          className="w-full h-[200px] p-4 border-2 border-gray-200 rounded-xl text-base outline-none font-inherit resize-y"          placeholder="Tempel teks Anda di sini untuk dianalisis..." />        <button onClick={analyzeText} disabled={loading}          className="mt-4 w-full bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white font-bold py-3 px-6 rounded-xl transition-all">{loading ? "Menganalisis..." : " Analisis Teks"}</button>        {error && (          <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-xl text-red-700 text-sm">{error}</div>        )}        {result && (          <div className={`mt-6 p-6 rounded-xl border ${getScoreBg(result.score)}`}>            <div className="text-center mb-4">              <span className="text-5xl">{getScoreEmoji(result.score)}</span>              <p className={`text-5xl font-extrabold mt-2 ${getScoreColor(result.score)}`}>                {result.score}%              </p>              <p className={`text-sm font-bold mt-1 ${getScoreColor(result.score)}`}>                {getScoreLabel(result.score)}              </p>            </div>            <div className="w-full bg-gray-200 rounded-full h-3 mt-4">              <div className={`h-3 rounded-full transition-all duration-700 ${                result.score < 30 ? "bg-green-500" : result.score < 60 ? "bg-yellow-500" : "bg-red-500"              }`} style={{width: `${result.score}%`}} />            </div>            <p className="mt-4 text-sm text-gray-700 leading-relaxed">{result.explanation}</p>          </div>        )}        <div className="mt-4 p-4 bg-gray-50 rounded-xl border border-gray-200">          <p className="text-xs text-gray-500">            💡 <strong>Tip:</strong> Paste complete text (200+ words) for best accuracy.            No tool is 100% accurate — use results as a reference.          </p>        </div>      </div>      <SEOContent content={seoContent} lang="id" />      <FAQSection faqs={faqs} lang="en" />      <RelatedTools tools={relatedTools} lang="en" />      <ShareButtons lang="id" />    </div>  );}