#!/usr/bin/env python3
"""Translate English related tools + labels for Turkish and Indonesian, then deploy."""
import os, re, json, subprocess, time

FIRST_PASS = True

TR_DICT = {
    "Age Calculator": "Yaş Hesaplama",
    "BMI Calculator": "BMI Hesaplama",
    "Calorie Calculator": "Kalori Hesaplama",
    "Unit Converter": "Birim Dönüştürücü",
    "Word Counter": "Kelime Sayacı",
    "Password Generator": "Şifre Oluşturucu",
    "QR Generator": "QR Kod Oluşturucu",
    "QR Code Generator": "QR Kod Oluşturucu",
    "QR Reader": "QR Kod Okuyucu",
    "Invoice Generator": "Fatura Oluşturucu",
    "Name Generator": "İsim Oluşturucu",
    "Random Number Generator": "Rastgele Sayı Oluşturucu",
    "Random Number": "Rastgele Sayı",
    "Stopwatch": "Kronometre",
    "Text Cleaner": "Metin Temizleyici",
    "Text Case": "Metin Büyük/Küçük Harf",
    "Text Case Converter": "Metin Büyük/Küçük Harf",
    "Text Compare": "Metin Karşılaştırma",
    "Base64 Encoder": "Base64 Kodlayıcı",
    "Hash Generator": "Hash Oluşturucu",
    "JSON Formatter": "JSON Biçimlendirici",
    "SEO Audit": "SEO Denetimi",
    "SEO Content Generator": "SEO İçerik Oluşturucu",
    "Compound Interest": "Bileşik Faiz",
    "Profit Margin": "Kar Marjı",
    "Currency Converter": "Döviz Çevirici",
    "Color Converter": "Renk Dönüştürücü",
    "Image Resizer": "Görsel Boyutlandırıcı",
    "Image Compressor": "Görsel Sıkıştırıcı",
    "Image to PDF": "Görselden PDF'e",
    "PDF Merger": "PDF Birleştirici",
    "PDF Splitter": "PDF Ayırıcı",
    "PDF Compressor": "PDF Sıkıştırıcı",
    "PDF to Word": "PDF'den Word'e",
    "Remove Background": "Arka Plan Kaldırıcı",
    "YouTube Thumbnail Downloader": "YouTube Küçük Resim İndirici",
    "WhatsApp Link": "WhatsApp Bağlantısı",
    "Number to Words": "Sayıyı Yazıya Çevir",
    "Bio Generator": "Biyografi Oluşturucu",
    "Hijri Converter": "Hicri Çevirici",
    "Qibla Direction": "Kıble Yönü",
    "Direction Qibla": "Kıble Yönü",
    "Prayer Times": "Namaz Vakitleri",
    "Tasbeeh Counter": "Tesbih Sayacı",
    "Fidyah Kaffarah": "Fidye Kefaret",
    "AI Content Detector": "AI İçerik Dedektörü",
    "Paraphrasing Tool": "Paraphrazlama Aracı",
    "Grammar Checker": "Dilbilgisi Denetleyicisi",
    "Markdown Editor": "Markdown Düzenleyici",
    "CSS Minifier": "CSS Küçültücü",
    "Encryption Tool": "Şifreleme Aracı",
    "Time Zone Converter": "Saat Dilimi Çevirici",
    "Timezone Converter": "Saat Dilimi Çevirici",
    "Lorem Ipsum": "Lorem Ipsum Oluşturucu",
    "Plagiarism Checker": "İntihal Denetleyicisi",
    "Keyword Research Tool": "Anahtar Kelime Araştırma Aracı",
    "Mortgage Calculator": "Mortgage Hesaplama",
    "Installment Calculator": "Taksit Hesaplama",
    "Loan Calculator": "Kredi Hesaplama",
    "Salary Calculator": "Maaş Hesaplama",
    "VAT Calculator": "KDV Hesaplama",
    "EMI Calculator": "EMI Hesaplama",
    "Gold Calculator": "Altın Hesaplama",
    "Ideal Weight": "İdeal Kilo",
    "Date Duration": "Tarih Farkı",
    "Percentage Calculator": "Yüzde Hesaplama",
    "Zakat Calculator": "Zekat Hesaplama",
    "Umrah Calculator": "Umre Hesaplama",
    "Fidyah Kaffarah": "Fidye Kefaret",
    "Qibla Camera": "Kıble Kamerası",
    "Hijri Converter": "Hicri Çevirici",
    "Typing Test": "Yazma Testi",
    "Tasbeeh Counter": "Tesbih Sayacı",
    "Text Tools": "Metin Araçları",
    "Islamic Tools": "İslami Araçlar",
    "Developer Tools": "Geliştirici Araçları",
    "Dev Tools": "Geliştirici Araçları",
    "SEO Tools": "SEO Araçları",
    "Generators": "Oluşturucular",
    "Converters": "Dönüştürücüler",
    "Calculators": "Hesaplayıcılar",
    "Free SEO audit and analysis tool for any website": "Herhangi bir web sitesi için ücretsiz SEO denetim ve analiz aracı",
    "Minify and format CSS code online for free": "CSS kodunu ücretsiz olarak küçültün ve biçimlendirin",
    "Find detailed information about any IP address": "Herhangi bir IP adresi hakkında detaylı bilgi bulun",
    "Write and edit Markdown with live preview": "Canlı önizleme ile Markdown yazın ve düzenleyin",
    "Write complete articles with AI": "AI ile komple makaleler yazın",
    "Reduce image file size while maintaining quality": "Kaliteyi koruyarak görsel boyutunu küçültün",
    "What is an SEO Audit?": "SEO Denetimi Nedir?",
    "Great site! Minor improvements only": "Harika site! Sadece küçük iyileştirmeler",
    "UPPERCASE": "BÜYÜK HARF",
    "Fix Spaces": "Boşlukları Düzelt",
    "Metric": "Metrik",
    "Imperial": "Emparyal",
    "Normal": "Normal",
    "Underweight": "Zayıf",
    "Overweight": "Fazla Kilolu",
    "Obese": "Obez",
    "Enter": "Girin",
    "Original": "Orijinal",
    "Result": "Sonuç",
}

ID_DICT = {
    "Age Calculator": "Kalkulator Usia",
    "BMI Calculator": "Kalkulator BMI",
    "Calorie Calculator": "Kalkulator Kalori",
    "Unit Converter": "Konverter Satuan",
    "Word Counter": "Penghitung Kata",
    "Password Generator": "Pembuat Kata Sandi",
    "QR Generator": "Pembuat QR",
    "QR Code Generator": "Pembuat Kode QR",
    "QR Reader": "Pembaca QR",
    "Invoice Generator": "Pembuat Faktur",
    "Name Generator": "Pembuat Nama",
    "Random Number Generator": "Pembuat Angka Acak",
    "Random Number": "Angka Acak",
    "Stopwatch": "Pengatur Waktu",
    "Text Cleaner": "Pembersih Teks",
    "Text Case": "Pengubah Huruf",
    "Text Case Converter": "Pengubah Huruf",
    "Text Compare": "Pembanding Teks",
    "Base64 Encoder": "Encoder Base64",
    "Hash Generator": "Generator Hash",
    "JSON Formatter": "Pemformat JSON",
    "SEO Audit": "Audit SEO",
    "SEO Content Generator": "Generator Konten SEO",
    "Compound Interest": "Bunga Majemuk",
    "Profit Margin": "Margin Laba",
    "Currency Converter": "Konverter Mata Uang",
    "Color Converter": "Konverter Warna",
    "Image Resizer": "Pengubah Ukuran Gambar",
    "Image Compressor": "Kompresor Gambar",
    "Image to PDF": "Gambar ke PDF",
    "PDF Merger": "Penggabung PDF",
    "PDF Splitter": "Pemisah PDF",
    "PDF Compressor": "Kompresor PDF",
    "PDF to Word": "PDF ke Word",
    "Remove Background": "Penghapus Latar Belakang",
    "YouTube Thumbnail Downloader": "Pengunduh Thumbnail YouTube",
    "WhatsApp Link": "Tautan WhatsApp",
    "Number to Words": "Angka ke Huruf",
    "Bio Generator": "Pembuat Bio",
    "Hijri Converter": "Konverter Hijriah",
    "Qibla Direction": "Arah Kiblat",
    "Direction Qibla": "Arah Kiblat",
    "Prayer Times": "Waktu Shalat",
    "Tasbeeh Counter": "Penghitung Tasbih",
    "Fidyah Kaffarah": "Fidyah Kaffarah",
    "AI Content Detector": "Detektor Konten AI",
    "Paraphrasing Tool": "Alat Parafrase",
    "Grammar Checker": "Pemeriksa Tata Bahasa",
    "Markdown Editor": "Editor Markdown",
    "CSS Minifier": "Pengecil CSS",
    "Encryption Tool": "Alat Enkripsi",
    "Enkripsi": "Enkripsi",
    "Enkripsi Teks": "Enkripsi Teks",
    "Time Zone Converter": "Konverter Zona Waktu",
    "Timezone Converter": "Konverter Zona Waktu",
    "Lorem Ipsum": "Lorem Ipsum",
    "Plagiarism Checker": "Pemeriksa Plagiarisme",
    "Keyword Research Tool": "Alat Riset Kata Kunci",
    "Mortgage Calculator": "Kalkulator Hipotek",
    "Installment Calculator": "Kalkulator Cicilan",
    "Loan Calculator": "Kalkulator Pinjaman",
    "Salary Calculator": "Kalkulator Gaji",
    "VAT Calculator": "Kalkulator PPN",
    "EMI Calculator": "Kalkulator EMI",
    "Gold Calculator": "Kalkulator Emas",
    "Ideal Weight": "Berat Ideal",
    "Date Duration": "Durasi Tanggal",
    "Percentage Calculator": "Kalkulator Persentase",
    "Zakat Calculator": "Kalkulator Zakat",
    "Umrah Calculator": "Kalkulator Umrah",
    "Qibla Camera": "Kamera Kiblat",
    "Typing Test": "Tes Mengetik",
    "Text Tools": "Alat Teks",
    "Islamic Tools": "Alat Islami",
    "Developer Tools": "Alat Pengembang",
    "Dev Tools": "Alat Pengembang",
    "SEO Tools": "Alat SEO",
    "Generators": "Pembuat",
    "Converters": "Konverter",
    "Calculators": "Kalkulator",
    "Daily Tools": "Alat Harian",
    "Other Tools": "Alat Lainnya",
    "New tool": "Alat Baru",
    "Segera Hadir": "Segera Hadir",
    "Tools": "Alat",
    "Free SEO audit and analysis tool for any website": "Alat audit dan analisis SEO gratis untuk situs web apa pun",
    "Minify and format CSS code online for free": "Perkecil dan format kode CSS online secara gratis",
    "Find detailed information about any IP address": "Temukan informasi detail tentang alamat IP apa pun",
    "Write and edit Markdown with live preview": "Tulis dan edit Markdown dengan pratinjau langsung",
    "Write complete articles with AI": "Tulis artikel lengkap dengan AI",
    "Reduce image file size while maintaining quality": "Kurangi ukuran file gambar sambil menjaga kualitas",
    "What is an SEO Audit?": "Apa itu Audit SEO?",
    "Great site! Minor improvements only": "Situs bagus! Hanya perbaikan kecil",
    "UPPERCASE": "HURUF BESAR",
    "Fix Spaces": "Perbaiki Spasi",
    "Metric": "Metrik",
    "Imperial": "Imperial",
    "Normal": "Normal",
    "Underweight": "Kurus",
    "Overweight": "Gemuk",
    "Obese": "Obesitas",
    "Enter": "Masukkan",
    "Original": "Asli",
    "Result": "Hasil",
    "Preview": "Pratinjau",
    "Warning": "Peringatan",
    "Running...": "Memproses...",
    "Checking...": "Memeriksa...",
    "Please enter text": "Silakan masukkan teks",
    "Please enter at least 20 characters": "Silakan masukkan minimal 20 karakter",
    "Please enter at least 50 characters": "Silakan masukkan minimal 50 karakter",
    "Please enter a keyword (at least 3 characters)": "Silakan masukkan kata kunci (minimal 3 karakter)",
    "Could not determine your location.": "Tidak dapat menentukan lokasi Anda.",
    "Could not detect your location. Make sure GPS is enabled.": "Tidak dapat mendeteksi lokasi Anda. Pastikan GPS aktif.",
    "Invalid coordinates": "Koordinat tidak valid",
    "Turn left": "Belok kiri",
    "Turn right": "Belok kanan",
    "Your Name": "Nama Anda",
    "Your Company": "Perusahaan Anda",
    "Client": "Klien",
}

def apply_dict(directory, dict_map, lang_code):
    """Apply dictionary-based fixes to all tools."""
    tools = sorted([d for d in os.listdir(directory) if os.path.isdir(os.path.join(directory, d))])
    fixed = 0
    
    for tool in tools:
        cf = os.path.join(directory, tool, "Client.tsx")
        if not os.path.exists(cf): continue
        with open(cf) as f:
            orig = f.read()
        content = orig
        
        # Apply dictionary - longest matches first
        for eng, trans in sorted(dict_map.items(), key=lambda x: -len(x[0])):
            content = content.replace('"' + eng + '"', '"' + trans + '"')
            content = content.replace("'" + eng + "'", "'" + trans + "'")
        
        if content != orig:
            with open(cf, "w") as f:
                f.write(content)
            fixed += 1
    
    print(f"{lang_code}: {fixed}/{len(tools)} fixed with dictionary")
    return fixed

def main():
    base = "/home/ops123/adwatak/src/app"
    
    # Phase 1: Dictionary pass for both
    tr_fixed = apply_dict(os.path.join(base, "tr/tools"), TR_DICT, "TR")
    id_fixed = apply_dict(os.path.join(base, "id/tools"), ID_DICT, "ID")
    
    print(f"\nTotal: TR={tr_fixed}, ID={id_fixed}")

if __name__ == "__main__":
    main()
