"use client";import { useState } from "react";import StructuredData, { speakableSchema, toolSchema, faqSchema, breadcrumbSchema,howToSchema } from "../../../components/StructuredData";import Breadcrumb from "../../../components/Breadcrumb";import ShareButtons from "../../../components/ShareButtons";import FAQSection from "../../../components/FAQSection";import RelatedTools from "../../../components/RelatedTools";import SEOContent from "../../../components/SEOContent";const faqs = [  { question: "İntihal Denetleyici nedir?", answer: "A free tool that detects copied or improperly cited text. Uses AI to analyze text originality, identify potential plagiarism, and provide improvement suggestions. Essential for writers, students, and academics." },  { question: "İntihal tespiti ne kadar doğrudur?", answer: "High accuracy exceeding 85%. The AI detects repetitive patterns, unusual phrasing, and unoriginal structures. However, no tool is 100% accurate — use it as a primary reference." },  { question: "Does it support Arabic and English?", answer: "Yes, fluently. Analyzes Arabic, English, and mixed-language texts with equal accuracy." },  { question: "What text length is needed?", answer: "Minimum 50 characters. Longer texts give more accurate results. Best with 200-2000 words for optimal accuracy." },  { question: "Is my data safe?", answer: "100% private. Text is sent for analysis only and is never stored. We keep no database of analyzed content." },  { question: "What is the Originality Score?", answer: "A percentage reflecting content authenticity. 90-100% = highly original. 70-89% = good. Below 70% = needs review and proper citation." },  { question: "Is it suitable for academic research?", answer: "Yes, ideal for students and researchers. Verify your work's originality before submission. Best used alongside proper citation tools." },  { question: "How to use the results?", answer: "Focus on suggestions to improve your text. Rewrite flagged sections. Add missing citations. Use regularly to improve your writing quality." },  { question: "Can translated content be detected?", answer: "Translation without citing the source is considered indirect plagiarism. The tool detects literal translations from known source patterns." },  { question: "Is it completely free?", answer: "Yes, 100% free. No registration, no usage limits, no paid plans. Just paste and check." },  { question: "What types of plagiarism does it detect?", answer: "Direct copying, paraphrased uncredited content, mosaic plagiarism, self-plagiarism, and improperly cited translations." },  { question: "How can I avoid plagiarism?", answer: "Paraphrase in your own words, use quotation marks for direct quotes, cite all sources, and use this tool to verify before publishing." },];const relatedTools = [  { title: "AI İçerik Dedektörü", icon: "🤖", href: "/en/tools/ai-content-detector" },  { title: "Paraphrazlama Aracı", icon: "✏️", href: "/en/tools/paraphrasing-tool" },  { title: "Dilbilgisi Denetleyicisi", icon: "📝", href: "/en/tools/grammar-checker" },  { title: "Kelime Sayacı", icon: "📊", href: "/en/tools/word-counter" },  { title: "Metin Karşılaştırma", icon: "⚖️", href: "/en/tools/text-compare" },  { title: "Metin Temizleyici", icon: "🧹", href: "/en/tools/text-cleaner" },];const seoContent=[
  "Ü",
  "c",
  "r",
  "e",
  "t",
  "s",
  "i",
  "z",
  " ",
  "İ",
  "n",
  "t",
  "i",
  "h",
  "a",
  "l",
  " ",
  "D",
  "e",
  "n",
  "e",
  "t",
  "l",
  "e",
  "y",
  "i",
  "c",
  "i",
  "s",
  "i",
  " ",
  "—",
  " ",
  "k",
  "o",
  "p",
  "y",
  "a",
  "l",
  "a",
  "n",
  "m",
  "ı",
  "ş",
  " ",
  "i",
  "ç",
  "e",
  "r",
  "i",
  "ğ",
  "i",
  " ",
  "t",
  "e",
  "s",
  "p",
  "i",
  "t",
  " ",
  "e",
  "d",
  "i",
  "n",
  " ",
  "v",
  "e",
  " ",
  "m",
  "e",
  "t",
  "i",
  "n",
  " ",
  "ö",
  "z",
  "g",
  "ü",
  "n",
  "l",
  "ü",
  "ğ",
  "ü",
  "n",
  "ü",
  " ",
  "d",
  "e",
  "ğ",
  "e",
  "r",
  "l",
  "e",
  "n",
  "d",
  "i",
  "r",
  "i",
  "n",
  ".",
  " ",
  "M",
  "e",
  "t",
  "n",
  "i",
  " ",
  "y",
  "a",
  "p",
  "ı",
  "ş",
  "t",
  "ı",
  "r",
  "ı",
  "n",
  " ",
  "v",
  "e",
  " ",
  "i",
  "n",
  "t",
  "i",
  "h",
  "a",
  "l",
  " ",
  "y",
  "ü",
  "z",
  "d",
  "e",
  "s",
  "i",
  ",",
  " ",
  "ö",
  "z",
  "g",
  "ü",
  "n",
  "l",
  "ü",
  "k",
  " ",
  "p",
  "u",
  "a",
  "n",
  "ı",
  ",",
  " ",
  "a",
  "l",
  "ı",
  "n",
  "t",
  "ı",
  " ",
  "s",
  "o",
  "r",
  "u",
  "n",
  "l",
  "a",
  "r",
  "ı",
  " ",
  "v",
  "e",
  " ",
  "i",
  "y",
  "i",
  "l",
  "e",
  "ş",
  "t",
  "i",
  "r",
  "m",
  "e",
  " ",
  "ö",
  "n",
  "e",
  "r",
  "i",
  "l",
  "e",
  "r",
  "i",
  " ",
  "d",
  "a",
  "h",
  "i",
  "l",
  " ",
  "a",
  "n",
  "ı",
  "n",
  "d",
  "a",
  " ",
  "a",
  "n",
  "a",
  "l",
  "i",
  "z",
  " ",
  "i",
  "ç",
  "i",
  "n",
  " ",
  "k",
  "o",
  "n",
  "t",
  "r",
  "o",
  "l",
  " ",
  "e",
  "t",
  "'",
  "i",
  " ",
  "t",
  "ı",
  "k",
  "l",
  "a",
  "y",
  "ı",
  "n",
  ".",
  "
",
  "Ö",
  "ğ",
  "r",
  "e",
  "n",
  "c",
  "i",
  "l",
  "e",
  "r",
  ",",
  " ",
  "a",
  "r",
  "a",
  "ş",
  "t",
  "ı",
  "r",
  "m",
  "a",
  "c",
  "ı",
  "l",
  "a",
  "r",
  ",",
  " ",
  "y",
  "a",
  "z",
  "a",
  "r",
  "l",
  "a",
  "r",
  " ",
  "v",
  "e",
  " ",
  "i",
  "ç",
  "e",
  "r",
  "i",
  "k",
  " ",
  "o",
  "l",
  "u",
  "ş",
  "t",
  "u",
  "r",
  "u",
  "c",
  "u",
  "l",
  "a",
  "r",
  " ",
  "i",
  "ç",
  "i",
  "n",
  " ",
  "g",
  "e",
  "r",
  "e",
  "k",
  "l",
  "i",
  "d",
  "i",
  "r",
  ".",
  " ",
  "Y",
  "a",
  "y",
  "ı",
  "n",
  "l",
  "a",
  "m",
  "a",
  "d",
  "a",
  "n",
  " ",
  "ö",
  "n",
  "c",
  "e",
  " ",
  "i",
  "ç",
  "e",
  "r",
  "i",
  "k",
  " ",
  "ö",
  "z",
  "g",
  "ü",
  "n",
  "l",
  "ü",
  "ğ",
  "ü",
  "n",
  "ü",
  " ",
  "d",
  "o",
  "ğ",
  "r",
  "u",
  "l",
  "a",
  "y",
  "ı",
  "n",
  ".",
  " ",
  "İ",
  "t",
  "i",
  "b",
  "a",
  "r",
  "ı",
  "n",
  "ı",
  "z",
  "ı",
  " ",
  "k",
  "o",
  "r",
  "u",
  "y",
  "u",
  "n",
  " ",
  "v",
  "e",
  " ",
  "t",
  "e",
  "l",
  "i",
  "f",
  " ",
  "h",
  "a",
  "k",
  "k",
  "ı",
  " ",
  "s",
  "o",
  "r",
  "u",
  "n",
  "l",
  "a",
  "r",
  "ı",
  "n",
  "d",
  "a",
  "n",
  " ",
  "k",
  "a",
  "ç",
  "ı",
  "n",
  "ı",
  "n",
  ".",
  "
",
  "Y",
  "a",
  "p",
  "a",
  "y",
  " ",
  "z",
  "e",
  "k",
  "a",
  " ",
  "d",
  "e",
  "s",
  "t",
  "e",
  "k",
  "l",
  "i",
  " ",
  "a",
  "n",
  "a",
  "l",
  "i",
  "z",
  ",",
  " ",
  "d",
  "o",
  "ğ",
  "r",
  "u",
  "d",
  "a",
  "n",
  " ",
  "k",
  "o",
  "p",
  "y",
  "a",
  "l",
  "a",
  "m",
  "a",
  "y",
  "ı",
  ",",
  " ",
  "k",
  "a",
  "y",
  "n",
  "a",
  "k",
  " ",
  "g",
  "ö",
  "s",
  "t",
  "e",
  "r",
  "i",
  "l",
  "m",
  "e",
  "m",
  "i",
  "ş",
  " ",
  "b",
  "a",
  "ş",
  "k",
  "a",
  " ",
  "s",
  "ö",
  "z",
  "c",
  "ü",
  "k",
  "l",
  "e",
  "r",
  "l",
  "e",
  " ",
  "i",
  "f",
  "a",
  "d",
  "e",
  " ",
  "e",
  "d",
  "i",
  "l",
  "m",
  "i",
  "ş",
  " ",
  "i",
  "ç",
  "e",
  "r",
  "i",
  "ğ",
  "i",
  " ",
  "v",
  "e",
  " ",
  "a",
  "l",
  "ı",
  "n",
  "t",
  "ı",
  " ",
  "s",
  "o",
  "r",
  "u",
  "n",
  "l",
  "a",
  "r",
  "ı",
  "n",
  "ı",
  " ",
  "t",
  "e",
  "s",
  "p",
  "i",
  "t",
  " ",
  "e",
  "d",
  "e",
  "r",
  ".",
  " ",
  "S",
  "o",
  "n",
  "u",
  "ç",
  "l",
  "a",
  "r",
  ",",
  " ",
  "i",
  "y",
  "i",
  "l",
  "e",
  "ş",
  "t",
  "i",
  "r",
  "m",
  "e",
  " ",
  "i",
  "ç",
  "i",
  "n",
  " ",
  "u",
  "y",
  "g",
  "u",
  "l",
  "a",
  "n",
  "a",
  "b",
  "i",
  "l",
  "i",
  "r",
  " ",
  "ö",
  "n",
  "e",
  "r",
  "i",
  "l",
  "e",
  "r",
  " ",
  "i",
  "ç",
  "e",
  "r",
  "i",
  "r",
  ".",
  "
",
  "A",
  "r",
  "a",
  "ç",
  ",",
  " ",
  "A",
  "r",
  "a",
  "p",
  "ç",
  "a",
  ",",
  " ",
  "İ",
  "n",
  "g",
  "i",
  "l",
  "i",
  "z",
  "c",
  "e",
  " ",
  "v",
  "e",
  " ",
  "k",
  "a",
  "r",
  "ı",
  "ş",
  "ı",
  "k",
  " ",
  "d",
  "i",
  "l",
  "l",
  "i",
  " ",
  "m",
  "e",
  "t",
  "i",
  "n",
  "l",
  "e",
  "r",
  "i",
  " ",
  "d",
  "e",
  "s",
  "t",
  "e",
  "k",
  "l",
  "e",
  "r",
  ".",
  " ",
  "A",
  "n",
  "a",
  "l",
  "i",
  "z",
  " ",
  "h",
  "ı",
  "z",
  "l",
  "ı",
  " ",
  "v",
  "e",
  " ",
  "d",
  "o",
  "ğ",
  "r",
  "u",
  "d",
  "u",
  "r",
  ".",
  " ",
  "Y",
  "a",
  "z",
  "m",
  "a",
  " ",
  "i",
  "ş",
  " ",
  "a",
  "k",
  "ı",
  "ş",
  "ı",
  "n",
  "ı",
  "z",
  "ı",
  "n",
  " ",
  "b",
  "i",
  "r",
  " ",
  "p",
  "a",
  "r",
  "ç",
  "a",
  "s",
  "ı",
  " ",
  "o",
  "l",
  "a",
  "r",
  "a",
  "k",
  " ",
  "k",
  "u",
  "l",
  "l",
  "a",
  "n",
  "ı",
  "n",
  ".",
  "
",
  "İ",
  "p",
  "u",
  "c",
  "u",
  ":",
  " ",
  "Ö",
  "n",
  "e",
  "m",
  "l",
  "i",
  " ",
  "h",
  "e",
  "r",
  "h",
  "a",
  "n",
  "g",
  "i",
  " ",
  "b",
  "i",
  "r",
  " ",
  "i",
  "ç",
  "e",
  "r",
  "i",
  "ğ",
  "i",
  " ",
  "y",
  "a",
  "y",
  "ı",
  "n",
  "l",
  "a",
  "m",
  "a",
  "d",
  "a",
  "n",
  " ",
  "ö",
  "n",
  "c",
  "e",
  " ",
  "b",
  "u",
  " ",
  "a",
  "r",
  "a",
  "c",
  "ı",
  " ",
  "k",
  "u",
  "l",
  "l",
  "a",
  "n",
  "ı",
  "n",
  ".",
  " ",
  "Ö",
  "n",
  "e",
  "r",
  "i",
  "l",
  "e",
  "r",
  "i",
  " ",
  "d",
  "i",
  "k",
  "k",
  "a",
  "t",
  "l",
  "i",
  "c",
  "e",
  " ",
  "i",
  "n",
  "c",
  "e",
  "l",
  "e",
  "y",
  "i",
  "n",
  ".",
  " ",
  "K",
  "a",
  "y",
  "n",
  "a",
  "k",
  "l",
  "a",
  "r",
  "ı",
  "n",
  "ı",
  "z",
  "ı",
  " ",
  "h",
  "e",
  "r",
  " ",
  "z",
  "a",
  "m",
  "a",
  "n",
  " ",
  "d",
  "ü",
  "z",
  "g",
  "ü",
  "n",
  " ",
  "ş",
  "e",
  "k",
  "i",
  "l",
  "d",
  "e",
  " ",
  "b",
  "e",
  "l",
  "i",
  "r",
  "t",
  "i",
  "n",
  ".",
];export default function Client() {  const [text, setText] = useState("");  const [result, setResult] = useState<any>(null);  const [loading, setLoading] = useState(false);  const [error, setError] = useState("");  const check = async () => {    if (text.trim().length < 50) { setError("Please enter at least 50 characters"); return; }    setError(""); setLoading(true); setResult(null);    try {      const res = await fetch("/api/plagiarism-checker", {        method: "POST", headers: { "Content-Type": "application/json" },        body: JSON.stringify({ text: text.trim(), lang: "tr" }),      });      if (!res.ok) throw new Error((await res.json()).error || "Analysis failed");      setResult(await res.json());    } catch (e: any) { setError(e.message || "Error occurred."); } finally { setLoading(false); }  };  const gc = (s: number) => s < 30 ? "text-green-600" : s < 60 ? "text-yellow-600" : "text-red-600";  const gb = (s: number) => s < 30 ? "bg-green-50 border-green-200" : s < 60 ? "bg-yellow-50 border-yellow-200" : "bg-red-50 border-red-200";  const ge = (s: number) => s < 30 ? "✅" : s < 60 ? "⚠️" : "🚫";  return (    <div className="max-w-[760px] mx-auto">      <StructuredData data={toolSchema("İntihal Denetleyicisi", "Check text originality and detect plagiarized content", "https://adwatak.cloud/tr/tools/plagiarism-checker", "tr", "Text Analysis")} />      <StructuredData data={faqSchema(faqs)} />      <StructuredData data={breadcrumbSchema([{name:"Home",url:"https://adwatak.cloud/en"},{name:"Metin Araçları",url:"https://adwatak.cloud/tr/category/text"},{name:"İntihal Denetleyicisi",url:"https://adwatak.cloud/tr/tools/plagiarism-checker"}])} />{/* GEO: HowTo — adim adim kullanim */}
      <StructuredData data={howToSchema("Bu araci nasil kullanirim", "Tarayicinizda calisan ucretsiz arac. Kayit gerektirmez.", [{name:"Araci acin",text:"Adwatak sitesinde bu arac sayfasina gidin"},{name:"Verilerinizi girin",text:"Gerekli alanlari doldurun"},{name:"Sonuc alin",text:"Hesapla veya olustur butonuna tiklayin"},{name:"Kullanin veya paylasin",text:"Sonucu kopyalayin, indirin veya paylasin"}],"bir dakikadan az","tr")} />
      {/* GEO: Speakable — AI/ses motorlari */}
      <StructuredData data={speakableSchema(["h1","h2","main"])} />
<Breadcrumb lang="tr" category="Metin Araçları" categorySlug="text" toolName="İntihal Denetleyici" />      <div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6">        <h1 className="text-2xl font-extrabold mb-1">🚫 İntihal Denetleyici</h1>        <p className="text-sm text-gray-500 mb-6">Detect copied content and assess text originality</p>        <textarea value={text} onChange={(e) => setText(e.target.value)}          className="w-full h-[200px] p-4 border-2 border-gray-200 rounded-xl text-base outline-none font-inherit resize-y"          placeholder="İntihal kontrolü için metninizi buraya yapıştırın..." />        <button onClick={check} disabled={loading}          className="mt-4 w-full bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400 text-white font-bold py-3 px-6 rounded-xl transition-all">          {loading ? "Checking..." : "🔍 Check"}        </button>        {error && <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-xl text-red-700 text-sm">{error}</div>}        {result && (          <>            <div className={`mt-6 p-6 rounded-xl border ${gb(result.score)}`}>              <div className="text-center mb-4">                <span className="text-5xl">{ge(result.score)}</span>                <p className={`text-5xl font-extrabold mt-2 ${gc(result.score)}`}>{result.score}%</p>              </div>              <div className="w-full bg-gray-200 rounded-full h-3 mt-4">                <div className={`h-3 rounded-full transition-all ${result.score < 30 ? "bg-green-500" : result.score < 60 ? "bg-yellow-500" : "bg-red-500"}`} style={{width:`${result.score}%`}} />              </div>            </div>            <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-3">              <div className="p-4 bg-white rounded-xl border border-gray-200">                <p className="text-xs text-gray-500 mb-1">Originality Score</p>                <p className={`text-2xl font-extrabold ${gc(100 - result.score)}`}>{result.originalScore ?? 100 - result.score}%</p>              </div>              {result.citationIssues?.length > 0 && (                <div className="p-4 bg-yellow-50 rounded-xl border border-yellow-200">                  <p className="text-xs font-bold text-yellow-800 mb-2">Citation Issues</p>                  {result.citationIssues.map((i: string, idx: number) => <p key={idx} className="text-xs text-yellow-700">• {i}</p>)}                </div>              )}            </div>            <p className="mt-4 text-sm text-gray-700 leading-relaxed">{result.explanation}</p>            {result.suggestions?.length > 0 && (              <div className="mt-4 p-4 bg-blue-50 border border-blue-200 rounded-xl">                <h3 className="text-sm font-bold text-blue-800 mb-2">💡 Suggestions</h3>                <ol className="text-xs text-blue-700 space-y-1 list-decimal list-inside">                  {result.suggestions.map((s: string, i: number) => <li key={i}>{s}</li>)}                </ol>              </div>            )}          </>        )}      </div>      <SEOContent content={seoContent} lang="tr" />      <FAQSection faqs={faqs} lang="tr" />      <RelatedTools tools={relatedTools} lang="tr" />      <ShareButtons lang="tr" />    </div>  );}