"use client";import{useState,useRef}from"react";import StructuredData,{toolSchema,faqSchema,breadcrumbSchema,speakableSchema,howToSchema }from"../../../components/StructuredData";import Breadcrumb from"../../../components/Breadcrumb";import ShareButtons from"../../../components/ShareButtons";import FAQSection from"../../../components/FAQSection";import RelatedTools from"../../../components/RelatedTools";import SEOContent from"../../../components/SEOContent";const faqs = [{"question":"Apa itu Kompresor Gambar?","answer":"Alat gratis yang mengurangi ukuran file gambar tanpa mengubah dimensi. Menggunakan kompresi canggih sambil menjaga kualitas yang dapat diterima. Semua di browser Anda."},{"question":"Apakah kompresi mengurangi kualitas?","answer":"Ya, tergantung pada tingkat kualitas. Kualitas tinggi = file lebih besar. Kualitas rendah = file lebih kecil. Sesuaikan slider untuk menemukan titik keseimbangan Anda."},{"question":"Format apa yang didukung?","answer":"JPG, PNG, WebP. Sesuaikan kualitas dari 0% hingga 100%."},{"question":"Apakah saya perlu mengunggah ke server Anda?","answer":"Tidak! Semua pemrosesan dilakukan di browser Anda menggunakan Canvas API. Gambar Anda tidak pernah meninggalkan perangkat Anda."},{"question":"Seberapa banyak saya bisa mengompres?","answer":"Gambar besar dapat dikompres 50-80%. Gambar kecil kompresinya lebih sedikit. Coba berbagai tingkat kualitas untuk melihat mana yang cocok."},{"question":"Kualitas terbaik untuk web?","answer":"70-80% memberikan keseimbangan yang sangat baik. Untuk cetak: 90-100%. Untuk email: 50-60%."},{"question":"Mana yang lebih baik untuk web, JPG atau WebP?","answer":"WebP: 25-35% lebih kecil dengan kualitas yang sama. Semua browser modern mendukungnya. JPG didukung secara universal."},{"question":"Apakah ini sepenuhnya gratis?","answer":"Ya, 100% gratis. Tanpa registrasi, tanpa batasan, tanpa watermark."},{"question":"Apakah ini berfungsi di ponsel?","answer":"Ya, responsif sepenuhnya di semua perangkat."},{"question":"Bagaimana cara menggunakannya?","answer":"Unggah gambar, sesuaikan slider kualitas, pilih format, dan kompres. Pratinjau perbandingan sebelum mengunduh."},{"question":"Apa perbedaan antara kompres dan ubah ukuran?","answer":"Kompres mengurangi ukuran file dengan mempertahankan dimensi. Ubah ukuran mengubah dimensi. Gunakan keduanya untuk hasil terbaik."},{"question":"Bisakah saya mengompres gambar besar?","answer":"Ya, hingga 20 megapiksel. Gambar yang lebih besar dapat memperlambat browser."}];const relatedTools=[{title:"Pengubah Ukuran Gambar",icon:"🖼️",href:"/id/tools/image-resizer"},{title:"Pengunduh Thumbnail YouTube",icon:"▶️",href:"/id/tools/youtube-thumbnail-downloader"},{title:"Gambar ke PDF",icon:"📄",href:"/id/tools/image-to-pdf"},{title:"Pembuat QR",icon:"🔳",href:"/id/tools/qr-generator"},];const seoContent=[
  "Kompresor Gambar Gratis — kurangi ukuran file gambar sambil menjaga kualitas.",
  "Unggah, sesuaikan kualitas, dan unduh.",
  "Semua di browser Anda, tanpa unggah ke server.",
  "Ideal untuk pemilik situs web dan blogger.",
  "Gambar yang dikompresi mempercepat pemuatan halaman dan meningkatkan peringkat Google.",
  "Kecepatan situs adalah faktor SEO yang penting.",
  "Mendukung JPG, PNG, WebP.",
  "Penggeser kualitas interaktif menampilkan hasil secara real-time.",
  "Bandingkan ukuran file sebelum dan sesudah kompresi.",
  "Semua pemrosesan dilakukan secara lokal di browser Anda menggunakan Canvas.",
  "Tanpa unggah ke server — privasi sepenuhnya terjamin.",
  "Tips: Gunakan WebP dengan kualitas 80% untuk web.",
  "Untuk foto gunakan JPG dengan kualitas 75%.",
  "Untuk grafis warna datar gunakan PNG.",
];export default function Client(){const[imageFile,setImageFile]=useState<File|null>(null);const[imageUrl,setImageUrl]=useState("");const[quality,setQuality]=useState(80);const[originalSize,setOriginalSize]=useState(0);const[compressedUrl,setCompressedUrl]=useState<string|null>(null);const[compressedSize,setCompressedSize]=useState(0);const[format,setFormat]=useState("webp");const canvasRef=useRef<HTMLCanvasElement>(null);const handleImage=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setImageFile(file);setOriginalSize(file.size);setImageUrl(URL.createObjectURL(file));setCompressedUrl(null);};const compress=()=>{if(!imageFile)return;const img=new Image();img.onload=()=>{const canvas=canvasRef.current!;canvas.width=img.width;canvas.height=img.height;const ctx=canvas.getContext("2d")!;ctx.drawImage(img,0,0);const mime=format==="jpg"?"image/jpeg":`image/${format}`;const dataUrl=canvas.toDataURL(mime,quality/100);setCompressedUrl(dataUrl);setCompressedSize(Math.round(dataUrl.split(",")[1].length*0.75));};img.src=imageUrl;};return(<div className="max-w-[760px] mx-auto"><StructuredData data={toolSchema("Kompresor Gambar","Kurangi ukuran file gambar sambil menjaga kualitas","https://adwatak.cloud/id/tools/image-compressor","en","Image Tools")}/><StructuredData data={faqSchema(faqs)}/><StructuredData data={breadcrumbSchema([{name:"Home",url:"https://adwatak.cloud/en"},{name:"Image Tools",url:"https://adwatak.cloud/id/tools/image"},{name:"Kompresor Gambar",url:"https://adwatak.cloud/id/tools/image-compressor"}])}/>{/* GEO: HowTo — step by step for AI engines */}
      <StructuredData data={howToSchema("Cara menggunakan alat ini", "Free online tool. Works directly in your browser. No registration required.", [{name:"Buka alat",text:"Arahkan ke halaman alat ini di Adawatak"},{name:"Masukkan data Anda",text:"Isi kolom yang diperlukan"},{name:"Dapatkan hasil",text:"Klik tombol hitung atau hasilkan"},{name:"Gunakan atau bagikan",text:"Salin, unduh, atau bagikan hasilnya"}],"kurang dari satu menit","id")} />
      {/* GEO: Speakable — AI/voice engines */}
      <StructuredData data={speakableSchema(["h1","h2","main"])} />
<Breadcrumb lang="id" category="Alat Lainnya" categorySlug="image" toolName="Kompresor Gambar"/><div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6"><h1 className="text-2xl font-extrabold mb-1">📦 Kompresor Gambar</h1><p className="text-sm text-gray-500 mb-6">Reduce image file size while maintaining acceptable quality</p><input type="file" accept="image/*" onChange={handleImage} className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-xl file:border-0 file:text-sm file:font-bold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 mb-4"/>{imageFile&&(<><div className="mb-4"><label className="text-xs text-gray-500 block mb-1">Kualitas: {quality}%</label><input type="range" min={1} max={100} value={quality} onChange={(e)=>setQuality(Number(e.target.value))} className="w-full accent-blue-600"/></div><div className="flex gap-3 mb-4"><select value={format} onChange={(e)=>setFormat(e.target.value)} className="p-2 border-2 border-gray-200 rounded-xl text-sm outline-none"><option value="webp">WebP</option><option value="png">PNG</option><option value="jpg">JPG</option></select><button onClick={compress} className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-6 rounded-xl transition-all">Kompres</button></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="p-4 bg-white rounded-xl border border-gray-200"><p className="text-xs text-gray-500 mb-1">Before</p><p className="text-sm font-bold text-gray-700">{originalSize>1024*1024?`${(originalSize/1024/1024).toFixed(1)}MB`:`${(originalSize/1024).toFixed(1)}KB`}</p></div>{compressedUrl&&(<div className="p-4 bg-green-50 rounded-xl border border-green-200"><p className="text-xs text-gray-500 mb-1">After</p><p className="text-sm font-bold text-green-700">{compressedSize>1024*1024?`${(compressedSize/1024/1024).toFixed(1)}MB`:`${(compressedSize/1024).toFixed(1)}KB`}</p>{originalSize>0&&<p className="text-xs text-green-600">Saved {Math.round((1-compressedSize/originalSize)*100)}%</p>}</div>)}</div>{compressedUrl&&(<div className="mt-4 text-center"><img src={compressedUrl} alt="Compressed" className="max-h-64 mx-auto rounded-xl border border-green-200 mb-2"/><a href={compressedUrl} download={`compressed.${format}`} className="inline-block bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-6 rounded-xl transition-all">📥 Download</a></div>)}</>)}<canvas ref={canvasRef} className="hidden"/></div><SEOContent content={seoContent} lang="id"/><FAQSection faqs={faqs} lang="id"/><RelatedTools tools={relatedTools} lang="id"/><ShareButtons lang="id"/></div>);}