"use client";import{useState}from"react";import StructuredData,{toolSchema,faqSchema,breadcrumbSchema,speakableSchema,howToSchema }from"../../../components/StructuredData";import Breadcrumb from"../../../components/Breadcrumb";import ShareButtons from"../../../components/ShareButtons";import FAQSection from"../../../components/FAQSection";import RelatedTools from"../../../components/RelatedTools";import SEOContent from"../../../components/SEOContent";const faqs = [{question:"Apa itu YouTube Thumbnail Downloader?",answer:"Alat gratis untuk mengunduh thumbnail video YouTube dalam berbagai resolusi. Cukup tempel URL video dan pilih ukuran yang diinginkan."},{question:"Apakah saya perlu perangkat lunak?",answer:"Tidak, alat ini 100% gratis dan bekerja langsung di browser Anda. Tidak perlu instalasi atau langganan."},{question:"Resolusi apa saja yang tersedia?",answer:"MaxRes (1920×1080) - kualitas tertinggi. HQ (480×360) - kualitas tinggi. MQ (320×180) - sedang. SD (640×480) - standar."},{question:"Apakah ini legal?",answer:"Ya, mengunduh thumbnail untuk penggunaan pribadi umumnya diperbolehkan. YouTube menyajikan gambar-gambar ini secara publik. Jangan gunakan untuk komersial tanpa izin."},{question:"Bagaimana cara mendapatkan URL video?",answer:"Buka video di YouTube, salin URL dari bilah alamat browser Anda, dan tempelkan di kolom input."},{question:"Apakah mendukung URL pendek?",answer:"Ya: youtube.com/watch?v=, youtu.be/, youtube.com/shorts/, youtube.com/embed/."},{question:"Resolusi terbaik?",answer:"MaxRes (1920×1080) adalah kualitas tertinggi. Tidak semua video memiliki thumbnail MaxRes. Coba HQ atau SD sebagai alternatif."},{question:"Format apa thumbnail-nya?",answer:"Semua thumbnail berformat JPG. Unduh langsung."},{question:"Bisakah saya menggunakan thumbnail di proyek saya?",answer:"Penggunaan pribadi: ya. Penggunaan komersial: periksa ketentuan YouTube dan hak pemilik video."},{question:"Bagaimana jika tidak ada thumbnail yang muncul?",answer:"Verifikasi URL video. Video pribadi atau yang dihapus mungkin tidak menampilkan thumbnail. Coba resolusi lain."},{question:"Apakah berfungsi di ponsel?",answer:"Ya, sepenuhnya responsif di semua perangkat."},{question:"Apakah benar-benar gratis?",answer:"Ya, 100% gratis. Tanpa registrasi, tanpa batasan, tanpa iklan."},];const relatedTools=[{title:"Pengubah Ukuran Gambar",icon:"🖼️",href:"/en/tools/image-resizer"},{title:"Kompresor Gambar",icon:"📦",href:"/en/tools/image-compressor"},{title:"Pembuat QR",icon:"🔳",href:"/en/tools/qr-generator"},{title:"Pembuat Kata Sandi",icon:"🔐",href:"/en/tools/password-generator"},];const seoContent=[
  "Pengunduh Thumbnail YouTube Gratis.",
  "Tempelkan URL video apa pun dan unduh thumbnail dalam 4 resolusi: MaxRes (1920×1080), HQ, MQ, SD.",
  "Tidak perlu mendaftar.",
  "Ideal untuk blogger, pembuat konten, dan pemasar.",
  "Gunakan thumbnail untuk artikel, presentasi, atau postingan media sosial.",
  "Sederhana dan cepat: tempel URL, pratinjau, pilih resolusi, unduh.",
  "Mendukung semua format URL YouTube.",
  "Mengekstrak ID video secara otomatis.",
  "Tips: Gunakan MaxRes untuk kualitas terbaik.",
  "Jika tidak tersedia, coba HQ.",
  "Thumbnail berkualitas tinggi meningkatkan tampilan konten Anda.",
];function getVideoId(url:string):string|null{const patterns=[/(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/|youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})/,/^([a-zA-Z0-9_-]{11})$/];for(const p of patterns){const m=url.match(p);if(m)return m[1];}return null;}export default function Client(){const[url,setUrl]=useState("");const[videoId,setVideoId]=useState<string|null>(null);const[error,setError]=useState("");const resolutions=[{key:"maxresdefault",label:"MaxRes (1920×1080)",quality:"Highest"},{key:"hqdefault",label:"HQ (480×360)",quality:"High"},{key:"mqdefault",label:"MQ (320×180)",quality:"Medium"},{key:"sddefault",label:"SD (640×480)",quality:"Standard"}];const handleLookup=()=>{setError("");const id=getVideoId(url.trim());if(!id){setError("Please enter a valid YouTube URL");return;}setVideoId(id);};return(<div className="max-w-[760px] mx-auto"><StructuredData data={toolSchema("Pengunduh Thumbnail YouTube","Unduh thumbnail video YouTube dalam resolusi tinggi for free","https://adwatak.cloud/id/tools/youtube-thumbnail-downloader","en","Image Tools")}/><StructuredData data={faqSchema(faqs)}/><StructuredData data={breadcrumbSchema([{name:"Home",url:"https://adwatak.cloud/en"},{name:"Image Tools",url:"https://adwatak.cloud/en/tools/image"},{name:"Pengunduh Thumbnail YouTube",url:"https://adwatak.cloud/id/tools/youtube-thumbnail-downloader"}])}/>{/* GEO: HowTo — step by step for AI engines */}
      <StructuredData data={howToSchema("Cara menggunakan alat ini", "Free online tool. Works directly in your browser. No registration required.", [{name:"Buka alat",text:"Arahkan ke halaman alat ini di Adawatak"},{name:"Masukkan data Anda",text:"Isi kolom yang diperlukan"},{name:"Dapatkan hasil",text:"Klik tombol hitung atau hasilkan"},{name:"Gunakan atau bagikan",text:"Salin, unduh, atau bagikan hasilnya"}],"kurang dari satu menit","id")} />
      {/* GEO: Speakable — AI/voice engines */}
      <StructuredData data={speakableSchema(["h1","h2","main"])} />
<Breadcrumb lang="en" category="Alat Lainnya" categorySlug="image" toolName="Pengunduh Thumbnail YouTube"/><div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6"><h1 className="text-2xl font-extrabold mb-1">▶️ Pengunduh Thumbnail YouTube</h1><p className="text-sm text-gray-500 mb-6">Download YouTube video thumbnails in high resolution</p><div className="flex gap-3"><input type="text" value={url} onChange={(e)=>setUrl(e.target.value)} placeholder="https://youtube.com/watch?v=..." className="flex-1 p-3 border-2 border-gray-200 rounded-xl text-sm outline-none" onKeyDown={(e)=>e.key==="Masukkan"&&handleLookup()}/><button onClick={handleLookup} className="bg-blue-600 hover:bg-blue-700 text-white font-bold px-6 py-3 rounded-xl transition-all">Cari</button></div>{error&&<div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-xl text-red-700 text-sm">{error}</div>}{videoId&&(<div className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-4">{resolutions.map((res)=>{const imgSrc=`https://img.youtube.com/vi/${videoId}/${res.key}.jpg`;return(<div key={res.key} className="p-4 bg-white rounded-xl border border-gray-200"><img src={imgSrc} alt={res.label} className="w-full rounded-lg mb-2" onError={(e)=>{(e.target as HTMLImageElement).style.display="none";}}/><p className="text-xs font-bold text-gray-700">{res.label}</p><p className="text-xs text-gray-500 mb-2">{res.quality}</p><a href={imgSrc} download={`thumbnail-${res.key}.jpg`} className="inline-block bg-green-600 hover:bg-green-700 text-white font-bold py-1.5 px-4 rounded-xl text-xs transition-all">📥 Download</a></div>);})}</div>)}</div><SEOContent content={seoContent} lang="id"/><FAQSection faqs={faqs} lang="en"/><RelatedTools tools={relatedTools} lang="en"/><ShareButtons lang="id"/></div>);}