"use client";import{useState}from"react";import StructuredData,{toolSchema,faqSchema,breadcrumbSchema,speakableSchema,howToSchema }from"../../../components/StructuredData";import Breadcrumb from"../../../components/Breadcrumb";import ShareButtons from"../../../components/ShareButtons";import FAQSection from"../../../components/FAQSection";import RelatedTools from"../../../components/RelatedTools";import SEOContent from"../../../components/SEOContent";const faqs = [{"question":"Apa itu Editor Markdown?","answer":"Alat gratis untuk menulis dan mengedit teks Markdown dengan pratinjau langsung. Markdown adalah bahasa pemformatan sederhana yang secara otomatis mengonversi ke HTML."},{"question":"Apa itu Markdown?","answer":"Bahasa markup ringan yang memungkinkan Anda menulis teks terformat (judul, daftar, tautan, gambar) menggunakan simbol sederhana. Digunakan di GitHub, Reddit, Notion, dan lainnya."},{"question":"Apakah saya perlu belajar Markdown?","answer":"Sangat mudah dipelajari dalam 5 menit. ## untuk judul, **teks** untuk tebal, [teks](url) untuk tautan, - untuk daftar. Pratinjau langsung menampilkan hasil secara instan."},{"question":"Apa perbedaan antara Markdown dan HTML?","answer":"Markdown lebih sederhana dan lebih cepat untuk ditulis. HTML lebih kuat. Markdown secara otomatis mengonversi ke HTML. Tulis dalam Markdown, dapatkan HTML siap pakai."},{"question":"Apa saja kasus penggunaan Markdown?","answer":"File README GitHub, dokumentasi proyek, penulisan blog, catatan pribadi, dokumen teknis, dan konten pendidikan."},{"question":"Bisakah saya menyalin hasilnya sebagai HTML?","answer":"Ya, ada tombol 'Salin HTML' yang menyalin teks terformat sebagai HTML siap pakai."},{"question":"Fitur apa saja yang didukung?","answer":"Judul H1-H6, tebal/miring, daftar terurut/tidak terurut, tautan, gambar, kode sebaris/blok, kutipan blok, dan garis horizontal."},{"question":"Apakah ini sepenuhnya gratis?","answer":"Ya, 100% gratis. Tanpa registrasi, tanpa batasan, tanpa iklan."},{"question":"Apakah ini berfungsi di ponsel?","answer":"Ya, responsif penuh dengan editor dan pratinjau berdampingan."},{"question":"Bisakah saya mengunduh hasilnya?","answer":"Ya, unduh sebagai file .md atau .html."}];const relatedTools=[{title:"Pemformat JSON",icon:"📋",href:"/id/tools/json-formatter"},{title:"Pengecil CSS",icon:"🎨",href:"/id/tools/css-minifier"},{title:"Generator Hash",icon:"#️⃣",href:"/id/tools/hash-generator"},{title:"Encoder Base64",icon:"🔄",href:"/id/tools/base64-encoder"},{title:"Audit SEO",icon:"🔍",href:"/id/tools/seo-audit"},];const seoContent=[
  "Editor Markdown Gratis dengan pratinjau langsung.",
  "Tulis dalam Markdown dan lihat hasil HTML yang terformat secara instan.",
  "Sempurna untuk pengembang, penulis, dan dokumentasi.",
  "Markdown adalah bahasa pemformatan paling populer di dunia teknologi.",
  "GitHub, Reddit, Notion, dan Slack semuanya mendukungnya.",
  "Pelajari sekali, gunakan di mana saja.",
  "Mendukung semua sintaks Markdown standar: judul, daftar, tautan, gambar, kode, kutipan blok.",
  "Pratinjau langsung instan — setiap perubahan langsung terlihat.",
  "Salin HTML langsung: tulis dalam Markdown, salin HTML untuk digunakan di situs web mana pun.",
  "Ideal untuk blogger dan pembuat konten.",
  "Tips: Tulis konten dalam Markdown terlebih dahulu, lalu salin HTML.",
  "Lebih cepat daripada menulis HTML secara manual dan lebih sedikit kesalahan.",
];function renderMarkdown(md:string):string{let h=md.replace(/^###### (.+)$/gm,"<h6>$1</h6>").replace(/^##### (.+)$/gm,"<h5>$1</h5>").replace(/^#### (.+)$/gm,"<h4>$1</h4>").replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h1>$1</h1>").replace(/\*\*\*(.+?)\*\*\*/g,"<strong><em>$1</em></strong>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/\*(.+?)\*/g,"<em>$1</em>").replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2" class="text-blue-600 hover:underline">$1</a>').replace(/!\[([^\]]*)\]\(([^)]+)\)/g,'<img src="$2" alt="$1" class="max-w-full rounded-lg" />').replace(/^---$/gm,"<hr class='my-4 border-gray-300' />").replace(/^> (.+)$/gm,'<blockquote class="border-l-4 border-blue-500 pl-4 text-gray-600 italic">$1</blockquote>').replace(/^[-*] (.+)$/gm,"<li>$1</li>").replace(/^\d+\. (.+)$/gm,"<li>$1</li>").replace(/\n\n/g,"</p><p>").replace(/\n/g,"<br />");h=h.replace(/((?:<li>.*?<\/li><br \/>?)+)/g,"<ul class='list-disc pl-5 my-2'>$1</ul>").replace(/<\/li><br \/>/g,"</li>");return"<p>"+h+"</p>";}export default function Client(){const[input,setInput]=useState("## Hello!\nWrite **Markdown** here...");const[copied,setCopied]=useState(false);const copyHTML=()=>{navigator.clipboard.writeText(renderMarkdown(input));setCopied(true);setTimeout(()=>setCopied(false),2000);};const download=(ext:string,content:string)=>{const blob=new Blob([content],{type:"text/plain"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`document.${ext}`;a.click();URL.revokeObjectURL(url);};return(<div className="max-w-[760px] mx-auto"><StructuredData data={toolSchema("Editor Markdown","Tulis dan edit Markdown dengan pratinjau langsung","https://adwatak.cloud/id/tools/markdown-editor","en","Alat Pengembang")}/><StructuredData data={faqSchema(faqs)}/><StructuredData data={breadcrumbSchema([{name:"Home",url:"https://adwatak.cloud/en"},{name:"Alat Pengembang",url:"https://adwatak.cloud/id/category/dev"},{name:"Editor Markdown",url:"https://adwatak.cloud/id/tools/markdown-editor"}])}/>{/* GEO: HowTo — step by step for AI engines */}
      <StructuredData data={howToSchema("Cara menggunakan alat ini", "Free online tool. Works directly in your browser. No registration required.", [{name:"Buka alat",text:"Arahkan ke halaman alat ini di Adawatak"},{name:"Masukkan data Anda",text:"Isi kolom yang diperlukan"},{name:"Dapatkan hasil",text:"Klik tombol hitung atau hasilkan"},{name:"Gunakan atau bagikan",text:"Salin, unduh, atau bagikan hasilnya"}],"kurang dari satu menit","id")} />
      {/* GEO: Speakable — AI/voice engines */}
      <StructuredData data={speakableSchema(["h1","h2","main"])} />
<Breadcrumb lang="id" category="Alat Pengembang" categorySlug="dev" toolName="Editor Markdown"/><div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6"><h1 className="text-2xl font-extrabold mb-1">📝 Markdown Editor</h1><p className="text-sm text-gray-500 mb-6">Tulis Markdown dan lihat pratinjau langsung</p><div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4"><textarea value={input} onChange={(e)=>setInput(e.target.value)} className="w-full h-[350px] p-4 border-2 border-gray-200 rounded-xl text-sm font-mono outline-none resize-y" placeholder="Tulis Markdown di sini..."/><div className="h-[350px] p-4 bg-white border-2 border-gray-200 rounded-xl overflow-y-auto text-sm leading-relaxed prose" dangerouslySetInnerHTML={{__html:renderMarkdown(input)}}/></div><div className="flex gap-3"><button onClick={copyHTML} className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-xl text-sm transition-all">{copied?" Tersalin!":" Salin HTML"}</button><button onClick={()=>download("md",input)} className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-xl text-sm transition-all"> Unduh .md</button><button onClick={()=>download("html",renderMarkdown(input))} className="bg-green-600 hover:bg-green-700 text-white font-bold py-2 px-4 rounded-xl text-sm transition-all"> Unduh .html</button></div></div><SEOContent content={seoContent} lang="id"/><FAQSection faqs={faqs} lang="id"/><RelatedTools tools={relatedTools} lang="id"/><ShareButtons lang="id"/></div>);}