"use client";import{useState}from"react";import StructuredData,{toolSchema,faqSchema,breadcrumbSchema,speakableSchema,howToSchema }from"../../../components/StructuredData";import Breadcrumb from"../../../components/Breadcrumb";import ShareButtons from"../../../components/ShareButtons";import FAQSection from"../../../components/FAQSection";import RelatedTools from"../../../components/RelatedTools";import SEOContent from"../../../components/SEOContent";const faqs=[{question:"What is CSS Minifier?",answer:"A free tool to minify (compress) and format CSS code. Minification removes whitespace and comments to reduce file size. Formatting organizes code for readability."},{question:"Why minify CSS?",answer:"Minification reduces file size by 30-60%, speeding up page loading. Site speed is a critical Google ranking factor and improves user experience."},{question:"What's the difference between Minify and Format?",answer:"Minify removes non-essential characters (spaces, comments) to make files smaller. Format adds indentation and spacing to make code human-readable."},{question:"Does minification affect functionality?",answer:"No. Minification only removes whitespace and comments. The code works exactly the same."},{question:"Expected savings?",answer:"30-60% of original file size. A 100KB file may become 40KB after minification."},{question:"Is it completely free?",answer:"Yes, 100% free. No registration, no limits, no ads."},{question:"Is my code safe?",answer:"Yes, everything runs in your browser. Code never leaves your device."},{question:"Does it support modern CSS?",answer:"Yes: CSS3, Flexbox, Grid, Animations, Variables, and all modern CSS features."},{question:"When to use Minify vs Format?",answer:"Minify: before uploading to server. Format: when reading or editing someone else's code."},{question:"How to use it?",answer:"Paste CSS code, choose Minify or Format. Results appear instantly with size statistics. Use the copy button."},];const relatedTools=[{title:"JSON Biçimlendirici",icon:"📋",href:"/en/tools/json-formatter"},{title:"Markdown Düzenleyici",icon:"📝",href:"/en/tools/markdown-editor"},{title:"Hash Oluşturucu",icon:"#️⃣",href:"/en/tools/hash-generator"},{title:"Base64 Kodlayıcı",icon:"🔄",href:"/en/tools/base64-encoder"},{title:"SEO Denetimi",icon:"🔍",href:"/en/tools/seo-audit"},];const seoContent=[
  "Ü",
  "c",
  "r",
  "e",
  "t",
  "s",
  "i",
  "z",
  " ",
  "C",
  "S",
  "S",
  " ",
  "K",
  "ü",
  "ç",
  "ü",
  "l",
  "t",
  "ü",
  "c",
  "ü",
  " ",
  "v",
  "e",
  " ",
  "B",
  "i",
  "ç",
  "i",
  "m",
  "l",
  "e",
  "n",
  "d",
  "i",
  "r",
  "i",
  "c",
  "i",
  ".",
  " ",
  "C",
  "S",
  "S",
  " ",
  "k",
  "o",
  "d",
  "u",
  "n",
  "u",
  " ",
  "y",
  "a",
  "p",
  "ı",
  "ş",
  "t",
  "ı",
  "r",
  "ı",
  "n",
  " ",
  "v",
  "e",
  " ",
  "a",
  "n",
  "ı",
  "n",
  "d",
  "a",
  " ",
  "k",
  "ü",
  "ç",
  "ü",
  "l",
  "t",
  "ü",
  "l",
  "m",
  "ü",
  "ş",
  " ",
  "v",
  "e",
  "y",
  "a",
  " ",
  "b",
  "i",
  "ç",
  "i",
  "m",
  "l",
  "e",
  "n",
  "d",
  "i",
  "r",
  "i",
  "l",
  "m",
  "i",
  "ş",
  " ",
  "b",
  "i",
  "r",
  " ",
  "s",
  "ü",
  "r",
  "ü",
  "m",
  " ",
  "a",
  "l",
  "ı",
  "n",
  ".",
  " ",
  "T",
  "a",
  "m",
  "a",
  "m",
  "e",
  "n",
  " ",
  "t",
  "a",
  "r",
  "a",
  "y",
  "ı",
  "c",
  "ı",
  "n",
  "ı",
  "z",
  "d",
  "a",
  " ",
  "ç",
  "a",
  "l",
  "ı",
  "ş",
  "ı",
  "r",
  ".",
  "
",
  "W",
  "e",
  "b",
  " ",
  "g",
  "e",
  "l",
  "i",
  "ş",
  "t",
  "i",
  "r",
  "i",
  "c",
  "i",
  "l",
  "e",
  "r",
  "i",
  " ",
  "i",
  "ç",
  "i",
  "n",
  " ",
  "i",
  "d",
  "e",
  "a",
  "l",
  "d",
  "i",
  "r",
  ".",
  " ",
  "K",
  "ü",
  "ç",
  "ü",
  "l",
  "t",
  "m",
  "e",
  ",",
  " ",
  "C",
  "S",
  "S",
  " ",
  "d",
  "o",
  "s",
  "y",
  "a",
  " ",
  "b",
  "o",
  "y",
  "u",
  "t",
  "u",
  "n",
  "u",
  " ",
  "%",
  "3",
  "0",
  "-",
  "6",
  "0",
  " ",
  "o",
  "r",
  "a",
  "n",
  "ı",
  "n",
  "d",
  "a",
  " ",
  "a",
  "z",
  "a",
  "l",
  "t",
  "a",
  "r",
  "a",
  "k",
  " ",
  "s",
  "i",
  "t",
  "e",
  " ",
  "h",
  "ı",
  "z",
  "ı",
  "n",
  "ı",
  " ",
  "a",
  "r",
  "t",
  "ı",
  "r",
  "ı",
  "r",
  ".",
  " ",
  "P",
  "e",
  "r",
  "f",
  "o",
  "r",
  "m",
  "a",
  "n",
  "s",
  " ",
  "i",
  "ç",
  "i",
  "n",
  " ",
  "h",
  "e",
  "r",
  " ",
  "b",
  "a",
  "y",
  "t",
  " ",
  "ö",
  "n",
  "e",
  "m",
  "l",
  "i",
  "d",
  "i",
  "r",
  ".",
  "
",
  "B",
  "i",
  "ç",
  "i",
  "m",
  "l",
  "e",
  "n",
  "d",
  "i",
  "r",
  "m",
  "e",
  ",",
  " ",
  "d",
  "a",
  "ğ",
  "ı",
  "n",
  "ı",
  "k",
  " ",
  "k",
  "o",
  "d",
  "u",
  " ",
  "u",
  "y",
  "g",
  "u",
  "n",
  " ",
  "g",
  "i",
  "r",
  "i",
  "n",
  "t",
  "i",
  "l",
  "e",
  "r",
  "l",
  "e",
  " ",
  "d",
  "ü",
  "z",
  "e",
  "n",
  "l",
  "e",
  "r",
  ".",
  " ",
  "B",
  "i",
  "r",
  "d",
  "e",
  "n",
  " ",
  "ç",
  "o",
  "k",
  " ",
  "k",
  "a",
  "y",
  "n",
  "a",
  "k",
  "t",
  "a",
  "n",
  " ",
  "g",
  "e",
  "l",
  "e",
  "n",
  " ",
  "d",
  "ü",
  "z",
  "e",
  "n",
  "s",
  "i",
  "z",
  " ",
  "k",
  "o",
  "d",
  "l",
  "a",
  "r",
  "l",
  "a",
  " ",
  "ç",
  "a",
  "l",
  "ı",
  "ş",
  "m",
  "a",
  "k",
  " ",
  "i",
  "ç",
  "i",
  "n",
  " ",
  "m",
  "ü",
  "k",
  "e",
  "m",
  "m",
  "e",
  "l",
  "d",
  "i",
  "r",
  ".",
  "
",
  "Ö",
  "n",
  "c",
  "e",
  "s",
  "i",
  " ",
  "v",
  "e",
  " ",
  "s",
  "o",
  "n",
  "r",
  "a",
  "s",
  "ı",
  " ",
  "b",
  "o",
  "y",
  "u",
  "t",
  " ",
  "i",
  "s",
  "t",
  "a",
  "t",
  "i",
  "s",
  "t",
  "i",
  "k",
  "l",
  "e",
  "r",
  "i",
  "n",
  "i",
  " ",
  "g",
  "ö",
  "s",
  "t",
  "e",
  "r",
  "i",
  "r",
  ".",
  " ",
  "S",
  "ı",
  "k",
  "ı",
  "ş",
  "t",
  "ı",
  "r",
  "m",
  "a",
  " ",
  "i",
  "ç",
  "i",
  "n",
  " ",
  "K",
  "ü",
  "ç",
  "ü",
  "l",
  "t",
  " ",
  "d",
  "ü",
  "ğ",
  "m",
  "e",
  "s",
  "i",
  ",",
  " ",
  "o",
  "k",
  "u",
  "n",
  "a",
  "b",
  "i",
  "l",
  "i",
  "r",
  "l",
  "i",
  "k",
  " ",
  "i",
  "ç",
  "i",
  "n",
  " ",
  "B",
  "i",
  "ç",
  "i",
  "m",
  "l",
  "e",
  "n",
  "d",
  "i",
  "r",
  " ",
  "d",
  "ü",
  "ğ",
  "m",
  "e",
  "s",
  "i",
  " ",
  "—",
  " ",
  "h",
  "e",
  "r",
  " ",
  "b",
  "i",
  "r",
  "i",
  " ",
  "t",
  "e",
  "k",
  " ",
  "t",
  "ı",
  "k",
  "l",
  "a",
  ".",
  "
",
  "İ",
  "p",
  "u",
  "c",
  "u",
  ":",
  " ",
  "S",
  "u",
  "n",
  "u",
  "c",
  "u",
  "y",
  "a",
  " ",
  "y",
  "ü",
  "k",
  "l",
  "e",
  "m",
  "e",
  "d",
  "e",
  "n",
  " ",
  "ö",
  "n",
  "c",
  "e",
  " ",
  "k",
  "ü",
  "ç",
  "ü",
  "l",
  "t",
  "ü",
  "n",
  ".",
  " ",
  "K",
  "o",
  "d",
  "u",
  " ",
  "o",
  "k",
  "u",
  "r",
  "k",
  "e",
  "n",
  " ",
  "b",
  "i",
  "ç",
  "i",
  "m",
  "l",
  "e",
  "n",
  "d",
  "i",
  "r",
  "i",
  "n",
  ".",
  " ",
  "H",
  "i",
  "ç",
  "b",
  "i",
  "r",
  "i",
  " ",
  "k",
  "o",
  "d",
  "u",
  "n",
  " ",
  "n",
  "a",
  "s",
  "ı",
  "l",
  " ",
  "ç",
  "a",
  "l",
  "ı",
  "ş",
  "t",
  "ı",
  "ğ",
  "ı",
  "n",
  "ı",
  " ",
  "d",
  "e",
  "ğ",
  "i",
  "ş",
  "t",
  "i",
  "r",
  "m",
  "e",
  "z",
  ".",
];function minify(css:string):string{return css.replace(/\/\*[\s\S]*?\*\//g,"").replace(/\s+/g," ").replace(/\s*([{}:;,])\s*/g,"$1").replace(/;\}/g,"}").trim();}function format(css:string):string{let indent=0,result="";const cleaned=css.replace(/\/\*[\s\S]*?\*\//g,"").trim();for(const p of cleaned.split(/([{}])/g)){if(p==="{"){result+=" {\n";indent++;}else if(p==="}"){indent=Math.max(0,indent-1);result+="\n"+"  ".repeat(indent)+"}";}else if(p.trim()){for(const r of p.split(";").filter(Boolean)){const t=r.trim();if(t)result+="\n"+"  ".repeat(indent)+t+";";}}}return result.trim();}export default function Client(){const[input,setInput]=useState("");const[output,setOutput]=useState("");const[mode,setMode]=useState<"minify"|"format">("minify");const[copied,setCopied]=useState(false);const processCSS=(m:"minify"|"format")=>{setMode(m);setOutput(m==="minify"?minify(input):format(input));};const copyOutput=()=>{navigator.clipboard.writeText(output);setCopied(true);setTimeout(()=>setCopied(false),2000);};return(<div className="max-w-[760px] mx-auto"><StructuredData data={toolSchema("CSS Küçültücü","CSS kodunu ücretsiz olarak küçültün ve biçimlendirin","https://adwatak.cloud/tr/tools/css-minifier","tr","Geliştirici Araçları")}/><StructuredData data={faqSchema(faqs)}/><StructuredData data={breadcrumbSchema([{name:"Home",url:"https://adwatak.cloud/en"},{name:"Geliştirici Araçları",url:"https://adwatak.cloud/tr/category/dev"},{name:"CSS Küçültücü",url:"https://adwatak.cloud/tr/tools/css-minifier"}])}/>{/* GEO: HowTo — adim adim kullanim */}
      <StructuredData data={howToSchema("Bu araci nasil kullanirim", "Tarayicinizda calisan ucretsiz arac. Kayit gerektirmez.", [{name:"Araci acin",text:"Adwatak sitesinde bu arac sayfasina gidin"},{name:"Verilerinizi girin",text:"Gerekli alanlari doldurun"},{name:"Sonuc alin",text:"Hesapla veya olustur butonuna tiklayin"},{name:"Kullanin veya paylasin",text:"Sonucu kopyalayin, indirin veya paylasin"}],"bir dakikadan az","tr")} />
      {/* GEO: Speakable — AI/ses motorlari */}
      <StructuredData data={speakableSchema(["h1","h2","main"])} />
<Breadcrumb lang="tr" category="Geliştirici Araçları" categorySlug="dev" toolName="CSS Küçültücü"/><div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6"><h1 className="text-2xl font-extrabold mb-1">🎨 CSS Sıkıştırıcı ve Biçimlendirici</h1><p className="text-sm text-gray-500 mb-6">CSS kodunu sıkıştırın veya biçimlendirin — ücretsiz çevrimiçi araç</p><div className="flex gap-3 mb-4"><button onClick={()=>processCSS("minify")} className={`font-bold py-2 px-6 rounded-xl transition-all ${mode==="minify"?"bg-blue-600 text-white":"bg-gray-100 text-gray-700 hover:bg-gray-200"}`}>🔽 Sıkıştır</button><button onClick={()=>processCSS("format")} className={`font-bold py-2 px-6 rounded-xl transition-all ${mode==="format"?"bg-blue-600 text-white":"bg-gray-100 text-gray-700 hover:bg-gray-200"}`}>📐 Biçimlendir</button></div><textarea value={input} onChange={(e)=>setInput(e.target.value)} className="w-full h-[150px] p-4 border-2 border-gray-200 rounded-xl text-sm font-mono outline-none resize-y" placeholder="CSS kodunu buraya yapıştırın..."/>{output&&(<div className="mt-4 p-4 bg-gray-50 rounded-xl border border-gray-200"><div className="flex items-center justify-between mb-2"><p className="text-xs text-gray-500">Size: {input.length} → {output.length} chars ({input.length>0?Math.round((1-output.length/input.length)*100):0}% saved)</p><button onClick={copyOutput} className="text-xs bg-blue-600 hover:bg-blue-700 text-white px-3 py-1 rounded-lg transition-all">{copied?"✅ Kopyalandı!":"📋 Kopyala"}</button></div><pre className="text-xs font-mono text-gray-800 whitespace-pre-wrap max-h-[300px] overflow-y-auto">{output}</pre></div>)}</div><SEOContent content={seoContent} lang="tr"/><FAQSection faqs={faqs} lang="tr"/><RelatedTools tools={relatedTools} lang="tr"/><ShareButtons lang="tr"/></div>);}