"use client";import{useState}from"react";import StructuredData,{toolSchema,faqSchema,breadcrumbSchema,speakableSchema,howToSchema }from"../../../components/StructuredData";import Breadcrumb from"../../../components/Breadcrumb";import ShareButtons from"../../../components/ShareButtons";import FAQSection from"../../../components/FAQSection";import RelatedTools from"../../../components/RelatedTools";import SEOContent from"../../../components/SEOContent";const faqs = [{question:"Apa itu CSS Minifier?",answer:"Alat gratis untuk meminifikasi (mengompres) dan memformat kode CSS. Minifikasi menghapus spasi dan komentar untuk mengurangi ukuran file. Pemformatan mengatur kode agar mudah dibaca."},{question:"Mengapa meminifikasi CSS?",answer:"Minifikasi mengurangi ukuran file sebesar 30-60%, mempercepat pemuatan halaman. Kecepatan situs adalah faktor peringkat Google yang penting dan meningkatkan pengalaman pengguna."},{question:"Apa perbedaan antara Minify dan Format?",answer:"Minify menghapus karakter yang tidak penting (spasi, komentar) untuk membuat file lebih kecil. Format menambahkan indentasi dan spasi agar kode mudah dibaca manusia."},{question:"Apakah minifikasi memengaruhi fungsionalitas?",answer:"Tidak. Minifikasi hanya menghapus spasi dan komentar. Kode bekerja persis sama."},{question:"Penghematan yang diharapkan?",answer:"30-60% dari ukuran file asli. File 100KB bisa menjadi 40KB setelah minifikasi."},{question:"Apakah ini sepenuhnya gratis?",answer:"Ya, 100% gratis. Tanpa registrasi, tanpa batasan, tanpa iklan."},{question:"Apakah kode saya aman?",answer:"Ya, semuanya berjalan di browser Anda. Kode tidak pernah meninggalkan perangkat Anda."},{question:"Apakah mendukung CSS modern?",answer:"Ya: CSS3, Flexbox, Grid, Animations, Variabel, dan semua fitur CSS modern."},{question:"Kapan menggunakan Minify vs Format?",answer:"Minify: sebelum mengunggah ke server. Format: saat membaca atau mengedit kode orang lain."},{question:"Bagaimana cara menggunakannya?",answer:"Tempel kode CSS, pilih Minify atau Format. Hasil muncul seketika dengan statistik ukuran. Gunakan tombol salin."},];const relatedTools=[{title:"Pemformat JSON",icon:"📋",href:"/id/tools/json-formatter"},{title:"Editor Markdown",icon:"📝",href:"/id/tools/markdown-editor"},{title:"Generator Hash",icon:"#️⃣",href:"/id/tools/hash-generator"},{title:"Encoder Base64",icon:"🔄",href:"/id/tools/base64-encoder"},{title:"Audit SEO",icon:"🔍",href:"/id/tools/seo-audit"},];const seoContent=[
  "Minifier & Formatter CSS Gratis.",
  "Tempel kode CSS dan dapatkan versi yang diminifikasi atau diformat secara instan.",
  "Berjalan sepenuhnya di browser Anda.",
  "Ideal untuk pengembang web.",
  "Minifikasi mengurangi ukuran file CSS sebesar 30-60%, meningkatkan kecepatan situs.",
  "Setiap byte penting untuk performa.",
  "Format merapikan kode yang berantakan dengan indentasi yang tepat.",
  "Sempurna untuk bekerja dengan kode yang tidak teratur dari berbagai sumber.",
  "Menampilkan statistik ukuran sebelum dan sesudah.",
  "Tombol Minify untuk kompresi, tombol Format untuk keterbacaan — masing-masing satu klik.",
  "Tips: Minify sebelum mengunggah ke server.",
  "Format saat membaca kode.",
  "Keduanya tidak mengubah cara kerja kode.",
];function minify(css:string):string{return css.replace(/\/\*[\s\S]*?\*\//g,"").replace(/\s+/g," ").replace(/\s*([{}:;,])\s*/g,"$1").replace(/;\}/g,"}").trim();}function format(css:string):string{let indent=0,result="";const cleaned=css.replace(/\/\*[\s\S]*?\*\//g,"").trim();for(const p of cleaned.split(/([{}])/g)){if(p==="{"){result+=" {\n";indent++;}else if(p==="}"){indent=Math.max(0,indent-1);result+="\n"+"  ".repeat(indent)+"}";}else if(p.trim()){for(const r of p.split(";").filter(Boolean)){const t=r.trim();if(t)result+="\n"+"  ".repeat(indent)+t+";";}}}return result.trim();}export default function Client(){const[input,setInput]=useState("");const[output,setOutput]=useState("");const[mode,setMode]=useState<"minify"|"format">("minify");const[copied,setCopied]=useState(false);const processCSS=(m:"minify"|"format")=>{setMode(m);setOutput(m==="minify"?minify(input):format(input));};const copyOutput=()=>{navigator.clipboard.writeText(output);setCopied(true);setTimeout(()=>setCopied(false),2000);};return(<div className="max-w-[760px] mx-auto"><StructuredData data={toolSchema("Pengecil CSS","Perkecil dan format kode CSS online secara gratis","https://adwatak.cloud/id/tools/css-minifier","en","Alat Pengembang")}/><StructuredData data={faqSchema(faqs)}/><StructuredData data={breadcrumbSchema([{name:"Home",url:"https://adwatak.cloud/en"},{name:"Alat Pengembang",url:"https://adwatak.cloud/id/category/dev"},{name:"Pengecil CSS",url:"https://adwatak.cloud/id/tools/css-minifier"}])}/>{/* GEO: HowTo — step by step for AI engines */}
      <StructuredData data={howToSchema("Cara menggunakan alat ini", "Free online tool. Works directly in your browser. No registration required.", [{name:"Buka alat",text:"Arahkan ke halaman alat ini di Adawatak"},{name:"Masukkan data Anda",text:"Isi kolom yang diperlukan"},{name:"Dapatkan hasil",text:"Klik tombol hitung atau hasilkan"},{name:"Gunakan atau bagikan",text:"Salin, unduh, atau bagikan hasilnya"}],"kurang dari satu menit","id")} />
      {/* GEO: Speakable — AI/voice engines */}
      <StructuredData data={speakableSchema(["h1","h2","main"])} />
<Breadcrumb lang="id" category="Alat Pengembang" categorySlug="dev" toolName="Pengecil CSS"/><div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6"><h1 className="text-2xl font-extrabold mb-1">🎨 Pemadat & Perapih CSS</h1><p className="text-sm text-gray-500 mb-6">Minify or format CSS code — free online tool</p><div className="flex gap-3 mb-4"><button onClick={()=>processCSS("minify")} className={`font-bold py-2 px-6 rounded-xl transition-all ${mode==="minify"?"bg-blue-600 text-white":"bg-gray-100 text-gray-700 hover:bg-gray-200"}`}> Padatkan</button><button onClick={()=>processCSS("format")} className={`font-bold py-2 px-6 rounded-xl transition-all ${mode==="format"?"bg-blue-600 text-white":"bg-gray-100 text-gray-700 hover:bg-gray-200"}`}> Rapikan</button></div><textarea value={input} onChange={(e)=>setInput(e.target.value)} className="w-full h-[150px] p-4 border-2 border-gray-200 rounded-xl text-sm font-mono outline-none resize-y" placeholder="Tempel kode CSS di sini..."/>{output&&(<div className="mt-4 p-4 bg-gray-50 rounded-xl border border-gray-200"><div className="flex items-center justify-between mb-2"><p className="text-xs text-gray-500">Size: {input.length} → {output.length} chars ({input.length>0?Math.round((1-output.length/input.length)*100):0}% saved)</p><button onClick={copyOutput} className="text-xs bg-blue-600 hover:bg-blue-700 text-white px-3 py-1 rounded-lg transition-all">{copied?" Tersalin!":" Salin"}</button></div><pre className="text-xs font-mono text-gray-800 whitespace-pre-wrap max-h-[300px] overflow-y-auto">{output}</pre></div>)}</div><SEOContent content={seoContent} lang="id"/><FAQSection faqs={faqs} lang="id"/><RelatedTools tools={relatedTools} lang="id"/><ShareButtons lang="id"/></div>);}