"use client";import { useState } from "react";import StructuredData, { speakableSchema, toolSchema, faqSchema, breadcrumbSchema,howToSchema } from "../../../components/StructuredData";import Breadcrumb from "../../../components/Breadcrumb";import ShareButtons from "../../../components/ShareButtons";import FAQSection from "../../../components/FAQSection";import RelatedTools from "../../../components/RelatedTools";import SEOContent from "../../../components/SEOContent";const faqs = [
  { question: "Apa itu Lorem Ipsum?", answer: "Teks placeholder mirip Latin yang digunakan dalam desain dan penerbitan sejak tahun 1500-an. Ini adalah versi acak dari 'de Finibus Bonorum et Malorum' karya Cicero (45 SM). Digunakan untuk mengisi ruang dan menunjukkan elemen visual tanpa menggunakan konten bermakna." },
  { question: "Apa itu Arabic Lorem?", answer: "Teks placeholder Arab menggunakan omong kosong aksara Arab yang menyerupai teks Arab asli. Penting untuk mendesain tata letak RTL (kanan-ke-kiri), menguji tipografi Arab, dan mendemonstrasikan konten Arab sebelum teks asli siap." },
  { question: "Mengapa menggunakan teks placeholder Arab?", answer: "Pengujian desain RTL: teks Arab mengalir dari kanan ke kiri, menggunakan bentuk huruf yang berbeda (initial, medial, final, isolated), memiliki tinggi baris yang berbeda, dan panjang kata yang berbeda dari bahasa Inggris. Menggunakan Lorem Ipsum Latin untuk tata letak Arab memberikan hasil desain yang menyesatkan." },
  { question: "Bagaimana Arabic Lorem berbeda dari Lorem Latin?", answer: "Arab: kata lebih panjang (biasanya 5-8 karakter), huruf saling menyambung (tulisan kursif), arah RTL, bagian huruf yang turun di bawah garis dasar, kebutuhan spasi yang berbeda, tanda diakritik (tashkeel). Semua memengaruhi tata letak. Generator kami menghasilkan teks mirip Arab yang realistis untuk desain RTL yang akurat." },
  { question: "Kapan menggunakan Arabic Lorem?", answer: "Mockup situs web RTL, prototipe aplikasi Arab, tata letak cetak untuk publikasi Arab, pengujian arah CSS (direction: rtl), pemilihan font (mencoba berbagai font Arab), dan mendemonstrasikan hierarki konten dalam bahasa Arab sebelum penulisan naskah." },
  { question: "Apakah Arabic Lorem memiliki arti?", answer: "Tidak — ini adalah omong kosong aksara Arab yang diacak. Tidak seperti Lorem Ipsum Latin (yang merupakan Cicero yang diacak), Arabic Lorem dihasilkan dari pola huruf Arab umum dan bentuk kata tanpa makna sebenarnya. Ini mencegah kebingungan saat demo klien." },
  { question: "Bagaimana ini berbeda dari teks Arab asli?", answer: "Teks Arab asli memiliki tata bahasa, makna, dan sambungan huruf yang tepat. Arabic Lorem hanya meniru bentuk visual — frekuensi huruf yang sama, panjang kata, dan aliran RTL. Gunakan hanya untuk desain, bukan untuk pengujian konten." },
  { question: "Bisakah saya menyesuaikan panjangnya?", answer: "Ya — pilih dari: paragraf pendek (30-50 kata), paragraf sedang (80-120 kata), paragraf panjang (150-200 kata), atau beberapa paragraf. Generator kami langsung membuat pengisi Arab yang tampak realistis." },
  { question: "Font Arab terbaik untuk digunakan?", answer: "Font web Arab populer: Noto Naskh Arabic, Amiri (untuk teks tradisional), Cairo (modern), Tajawal (bersih), Almarai (sangat populer — 5 ketebalan), dan Readex Pro (font variabel). Uji dengan Lorem kami untuk melihat pratinjau tampilan font." },
  { question: "Arabic Lorem untuk media sosial?", answer: "Berguna untuk: mendesain postingan media sosial dalam bahasa Arab, menguji tata letak salinan iklan Arab, membuat mockup postingan Instagram/Facebook, dan mendemonstrasikan konten Arab dalam presentasi klien. Generator kami menghasilkan panjang yang sesuai." },
  { question: "Berapa jumlah kata Arab terbaik untuk pengujian desain?", answer: "Judul: 2-5 kata. Subjudul: 5-8 kata. Teks isi: 50-150 kata per bagian. Kartu: 15-25 kata. Tombol: 1-3 kata. Uji dengan jumlah kata yang realistis untuk evaluasi desain terbaik." },
  { question: "Bagaimana menggunakan ini untuk pengujian CSS RTL?", answer: "Hasilkan Arabic Lorem, terapkan ke elemen dengan direction: rtl. Uji: perataan teks (start bekerja lebih baik daripada left/right), perilaku overflow (kata-kata Arab lebih panjang), tinggi baris (1.8 lebih baik daripada 1.5 untuk bahasa Arab), dan padding/margin di sekitar teks." }
];const relatedTools = [
  { title: "Penghitung Kata", icon: "📝", href: "/id/tools/word-counter" },
  { title: "Kapitalisasi Teks", icon: "🔤", href: "/id/tools/text-case" },
  { title: "Pembersih Teks", icon: "🧹", href: "/id/tools/text-cleaner" },
  { title: "Pembanding Teks", icon: "📋", href: "/id/tools/text-compare" },
  { title: "Angka ke Kata", icon: "🔢", href: "/id/tools/number-to-words" },
  { title: "Pengatur Waktu", icon: "⏱️", href: "/id/tools/stopwatch" },
];const seoContent = [
  "Generator Lorem Ipsum Arab gratis kami menciptakan teks placeholder skrip Arab yang realistis untuk pengujian desain RTL. Sempurna untuk mendesain situs web, aplikasi, dan materi cetak dalam bahasa Arab, Urdu, Persia (Farsi), dan skrip kanan-ke-kiri lainnya.",
  "Mengapa Lorem Arab penting: Lorem Ipsum Latin tidak cocok untuk tata letak Arab. Skrip Arab memiliki panjang kata yang berbeda (rata-rata 5-8 karakter vs 3-5 dalam bahasa Inggris), tinggi baris yang berbeda, kebutuhan spasi yang berbeda, dan mengalir dari kanan ke kiri. Pengujian dengan pengisi skrip Arab asli mengungkap masalah tata letak yang disembunyikan oleh teks Latin.",
  "Kasus penggunaan: (1) Desain situs web RTL — uji header, teks isi, kartu, dan formulir. (2) Prototipe aplikasi seluler — bandingkan tata letak Arab vs Inggris. (3) Desain cetak — uji tata letak majalah dan brosur Arab. (4) Pengujian arah CSS — verifikasi perilaku properti direction: rtl. (5) Pemilihan font — pratinjau font Arab dalam konteks.",
  "Generator kami menciptakan teks skrip Arab yang acak namun realistis. Ini menggunakan pola huruf Arab yang umum, distribusi panjang kata, dan kombinasi karakter untuk meniru bentuk teks Arab asli. Teks ini dirancang untuk pengujian visual, bukan untuk makna atau keterbacaan.",
  "Terkait: Gunakan Penghitung Kata kami untuk mengukur jumlah kata Lorem Arab. Alat Text Case membantu menguji format yang berbeda. Pembersih Teks menghapus elemen yang tidak diinginkan dari mockup. Lengkapi alur kerja desain Anda dari placeholder hingga konten akhir.",
  "Desain web RTL semakin berkembang — pengguna internet Arab melebihi 240 juta. Pengujian dengan teks placeholder yang realistis menangkap 80% bug tata letak RTL sebelum peluncuran. Generator Lorem Arab kami gratis, instan, dan tidak memerlukan pendaftaran."
];export default function Client() {  const [count, setCount] = useState(3);  const [result, setResult] = useState("");  const words = [    "السلام", "عليكم", "مرحبا", "أهلا", "بكم", "معاً", "نحو", "التقدم", "في", "عالم", "التكنولوجيا",    "المستقبل", "اليوم", "غدا", "رقمي", "إبداع", "تصميم", "تجربة", "مستخدم", "تطوير", "ويب",    "موقع", "تطبيق", "نظام", "برمجة", "بيانات", "ذكاء", "اصطناعي", "تعلم", "آلة", "شبكة",    "أمان", "خصوصية", "محتوى", "قيمة", "جودة", "تطبيق", "حلول", "برمجية", "لوحة", "تحكم",    "إدارة", "أدوات", "منصة", "خيارات", "عرض", "تقارير", "إحصائيات", "تحليل", "متقدم", "مبتكر",    "فريق", "عمل", "مشروع", "هدف", "رؤية", "رسالة", "استراتيجية", "تنفيذ", "نتائج", "قياس",    "تقييم", "تحسين", "تطوير", "مستمر", "إنجاز", "نجاح", "تميز", "ريادة", "ريادة", "أعمال",    "سوق", "منتج", "خدمة", "عميل", "شريك", "مستثمر", "مورّد", "مورد", "موارد", "بشرية",    "تسويق", "مبيعات", "دعم", "تقني", "تواصل", "اجتماعي", "إعلان", "عروض", "أسعار", "ميزانية"  ];  const generate = () => {    const paragraphs: string[] = [];    for (let p = 0; p < count; p++) {      const len = 25 + Math.floor(Math.random() * 15);      const sentence: string[] = [];      for (let i = 0; i < len; i++) sentence.push(words[Math.floor(Math.random() * words.length)]);      paragraphs.push(sentence.join(" ") + ".");    }    setResult(paragraphs.join("\n\n"));  };  const schemaName = "مولد النصوص العربية";const schemaDesc = `Online مولد النصوص العربية - free tool`;const schemaCategory = "Utility";const schemaUrl = "https://adwatak.cloud/id/tools/arabic-lorem";const breadcrumbItems = [  { name: "Home", url: "https://adwatak.cloud/id" },  { name: "Alat Teks", url: "https://adwatak.cloud/id/category/calculators" },  { name: "مولد النصوص العربية", url: "https://adwatak.cloud/id/tools/arabic-lorem" },];return (      <div className="max-w-[760px] mx-auto" dir="rtl">        <StructuredData data={toolSchema(schemaName, schemaDesc, schemaUrl, 'en', schemaCategory)} />        <StructuredData data={faqSchema(faqs)} />        <StructuredData data={breadcrumbSchema(breadcrumbItems)} />{/* GEO: HowTo — step by step for AI engines */}
      <StructuredData data={howToSchema("Cara menggunakan alat ini", "Free online tool. Works directly in your browser. No registration required.", [{name:"Buka alat",text:"Arahkan ke halaman alat ini di Adawatak"},{name:"Masukkan data Anda",text:"Isi kolom yang diperlukan"},{name:"Dapatkan hasil",text:"Klik tombol hitung atau hasilkan"},{name:"Gunakan atau bagikan",text:"Salin, unduh, atau bagikan hasilnya"}],"kurang dari satu menit","id")} />
      {/* GEO: Speakable — AI/voice engines */}
      <StructuredData data={speakableSchema(["h1","h2","main"])} />
<Breadcrumb category="Alat Teks" categorySlug="text-tools" toolName="Generator Lorem Arab" />      <div className="bg-white rounded-2xl border border-gray-200 p-8 mb-6">        <h1 className="text-2xl font-extrabold mb-1">📜 Generator Teks Arab</h1>        <p className="text-sm text-gray-500 mb-6">Generator Lorem Ipsum Arab untuk pengujian desain RTL</p>        <div className="mb-4">          <label className="block text-sm font-semibold text-gray-700 mb-1.5">Paragraf</label>          <select value={count} onChange={(e) => setCount(parseInt(e.target.value))} className="w-full p-3 border-2 border-gray-200 rounded-xl text-lg outline-none bg-white">            <option value="1">1 Paragraph</option>            <option value="2">2 Paragraphs</option>            <option value="3">3 Paragraphs</option>            <option value="4">4 Paragraphs</option>            <option value="5">5 Paragraphs</option>          </select>        </div>        <button onClick={generate} className="bg-blue-600 text-white font-bold p-3 rounded-xl border-none text-lg w-full cursor-pointer">Hasilkan Teks Arab</button>      </div>      {result && (        <div className="bg-gray-50 rounded-xl p-5 border border-gray-200 mb-6" dir="rtl">          <p className="text-sm leading-8 whitespace-pre-wrap" style={{ fontFamily: "'Noto Naskh Arabic', 'Traditional Arabic', serif" }}>{result}</p>          <button onClick={() =>navigator.clipboard.writeText(result)} className="mt-3 bg-gray-700 text-white font-semibold px-4 py-1.5 rounded-xl border-none text-sm cursor-pointer">Salin Teks</button>        </div>      )}      <SEOContent content={seoContent} />      <FAQSection faqs={faqs} />      <RelatedTools tools={relatedTools} />    <ShareButtons lang="id" />    </div>  );}