/**
 * Tool metadata for SEO — shared across all tools
 * Each tool gets: title, description, category, breadcrumb path
 */

export interface ToolMeta {
  slug: string;
  nameAr: string;
  nameEn: string;
  nameTr: string;
  descAr: string;
  descEn: string;
  descTr: string;
  categoryAr: string;
  categoryEn: string;
  categoryTr: string;
  categorySlug: string;
  schemaCategory: string;
}

export const TOOLS_META: Record<string, ToolMeta> = {
  "mortgage-calculator": {
    slug: "mortgage-calculator",
    nameAr: "حاسبة القرض العقاري",
    nameEn: "Mortgage Calculator",
    nameTr: "Konut Kredisi Hesaplama",
    descAr: "احسب القسط الشهري للقرض العقاري مع جدول الاستهلاك التفصيلي — حاسبة مجانية بالعربي للسعودية والإمارات ومصر",
    descEn: "Calculate your mortgage monthly payment with full amortization schedule — free Arabic mortgage calculator",
    descTr: "Konut kredisi aylık ödemenizi detaylı amortisman tablosuyla hesaplayın — ücretsiz konut kredisi hesaplama aracı",
    categoryAr: "الحاسبات المالية",
    categoryEn: "Financial Calculators",
    categoryTr: "Finansal Hesaplamalar",
    categorySlug: "calculators",
    schemaCategory: "Finance",
  },
  "loan-calculator": {
    slug: "loan-calculator",
    nameAr: "حاسبة القرض الشخصي",
    nameEn: "Personal Loan Calculator",
    nameTr: "Kişisel Kredi Hesaplama",
    descAr: "احسب القسط الشهري للقرض الشخصي مع إجمالي الفائدة — مجاني بدون تسجيل",
    descEn: "Calculate personal loan monthly payments with total interest — free, no signup",
    descTr: "Kişisel kredi aylık ödemelerinizi toplam faizle hesaplayın — ücretsiz, kayıt gerekmez",
    categoryAr: "الحاسبات المالية",
    categoryEn: "Financial Calculators",
    categoryTr: "Finansal Hesaplamalar",
    categorySlug: "calculators",
    schemaCategory: "Finance",
  },
  "installment-calculator": {
    slug: "installment-calculator",
    nameAr: "حاسبة التقسيط",
    nameEn: "Installment Calculator",
    nameTr: "Taksit Hesaplama",
    descAr: "احسب قيمة القسط الشهري لأي عملية تقسيط — سيارات، أجهزة، مشتريات",
    descEn: "Calculate installment payments for any purchase — cars, electronics, shopping",
    descTr: "Herhangi bir alışveriş için taksit ödemelerini hesaplayın — araba, elektronik, alışveriş",
    categoryAr: "الحاسبات المالية",
    categoryEn: "Financial Calculators",
    categoryTr: "Finansal Hesaplamalar",
    categorySlug: "calculators",
    schemaCategory: "Finance",
  },
  "emi-calculator": {
    slug: "emi-calculator",
    nameAr: "حاسبة EMI",
    nameEn: "EMI Calculator",
    nameTr: "EMI Hesaplama",
    descAr: "احسب القسط الشهري الثابت (EMI) للقروض — معادغة دقيقة مع جدول تفصيلي",
    descEn: "Calculate Equated Monthly Installment (EMI) for loans — precise formula with detailed schedule",
    descTr: "Krediler için Eşit Aylık Taksit (EMI) hesaplayın — hassas formül ve detaylı tablo",
    categoryAr: "الحاسبات المالية",
    categoryEn: "Financial Calculators",
    categoryTr: "Finansal Hesaplamalar",
    categorySlug: "calculators",
    schemaCategory: "Finance",
  },
  "profit-margin": {
    slug: "profit-margin",
    nameAr: "حاسبة هامش الربح",
    nameEn: "Profit Margin Calculator",
    nameTr: "Kâr Marjı Hesaplama",
    descAr: "احسب هامش الربح والمارك أب ونقطة التعادل — أداة أساسية لأصحاب المشاريع الصغيرة",
    descEn: "Calculate profit margin, markup, and breakeven — essential tool for small businesses",
    descTr: "Kâr marjı, kar oranı ve başabaş noktasını hesaplayın — küçük işletmeler için temel araç",
    categoryAr: "الحاسبات المالية",
    categoryEn: "Financial Calculators",
    categoryTr: "Finansal Hesaplamalar",
    categorySlug: "calculators",
    schemaCategory: "Finance",
  },
  "vat-calculator": {
    slug: "vat-calculator",
    nameAr: "حاسبة الضريبة المضافة",
    nameEn: "VAT Calculator",
    nameTr: "KDV Hesaplama",
    descAr: "احسب ضريبة القيمة المضافة VAT — السعودية 15%، الإمارات 5%، مصر 14%، البحرين 10%",
    descEn: "Calculate VAT — Saudi Arabia 15%, UAE 5%, Egypt 14%, Bahrain 10%",
    descTr: "KDV hesaplayın — Suudi Arabistan %15, BAE %5, Mısır %14, Bahreyn %10",
    categoryAr: "الحاسبات المالية",
    categoryEn: "Financial Calculators",
    categoryTr: "Finansal Hesaplamalar",
    categorySlug: "calculators",
    schemaCategory: "Finance",
  },
  "salary-calculator": {
    slug: "salary-calculator",
    nameAr: "حاسبة الراتب الصافي",
    nameEn: "Net Salary Calculator",
    nameTr: "Net Maaş Hesaplama",
    descAr: "احسب راتبك الصافي بعد التأمينات والاستقطاعات — السعودية والخليج",
    descEn: "Calculate net salary after insurance and deductions — Saudi Arabia & Gulf",
    descTr: "Sigorta ve kesintiler sonrası net maaşınızı hesaplayın — Suudi Arabistan ve Körfez",
    categoryAr: "الحاسبات المالية",
    categoryEn: "Financial Calculators",
    categoryTr: "Finansal Hesaplamalar",
    categorySlug: "calculators",
    schemaCategory: "Finance",
  },
  "compound-interest": {
    slug: "compound-interest",
    nameAr: "حاسبة الفائدة المركبة",
    nameEn: "Compound Interest Calculator",
    nameTr: "Bileşik Faiz Hesaplama",
    descAr: "احسب عائد استثمارك مع الفائدة المركبة — نمو الادخار والاستثمار بمرور الوقت",
    descEn: "Calculate investment returns with compound interest — savings growth over time",
    descTr: "Bileşik faizle yatırım getirilerinizi hesaplayın — zaman içinde tasarruf büyümesi",
    categoryAr: "الحاسبات المالية",
    categoryEn: "Financial Calculators",
    categoryTr: "Finansal Hesaplamalar",
    categorySlug: "calculators",
    schemaCategory: "Finance",
  },
  "gold-calculator": {
    slug: "gold-calculator",
    nameAr: "حاسبة الذهب",
    nameEn: "Gold Calculator",
    nameTr: "Altın Hesaplama",
    descAr: "احسب قيمة الذهب بالريال — زكاة الذهب والنصاب وسعر الجرام اليوم",
    descEn: "Calculate gold value in SAR — gold zakat, nisab, and today's per gram price",
    descTr: "Altın değerini TL/USD cinsinden hesaplayın — altın zekatı, nisap ve gram fiyatı",
    categoryAr: "الحاسبات المالية",
    categoryEn: "Financial Calculators",
    categoryTr: "Finansal Hesaplamalar",
    categorySlug: "calculators",
    schemaCategory: "Finance",
  },
  "car-installment": {
    slug: "car-installment",
    nameAr: "حاسبة تقسيط السيارة",
    nameEn: "Car Installment Calculator",
    nameTr: "Araba Taksit Hesaplama",
    descAr: "احسب أقساط تمويل السيارة — مع الدفعة الأولى ونسبة الفائدة ومدة التمويل",
    descEn: "Calculate car loan installments — with down payment, interest rate, and financing period",
    descTr: "Araba kredisi taksitlerini hesaplayın — peşinat, faiz oranı ve vade ile",
    categoryAr: "الحاسبات المالية",
    categoryEn: "Financial Calculators",
    categoryTr: "Finansal Hesaplamalar",
    categorySlug: "calculators",
    schemaCategory: "Finance",
  },
  "inheritance-calculator": {
    slug: "inheritance-calculator",
    nameAr: "حاسبة الميراث الإسلامي",
    nameEn: "Islamic Inheritance Calculator",
    nameTr: "İslami Miras Hesaplama",
    descAr: "احسب أنصبة الميراث حسب الشريعة الإسلامية — الفرائض والعصبات وذوي الأرحام",
    descEn: "Calculate Islamic inheritance shares according to Sharia — Fara'id, Asabat, and Dhawu al-Arham",
    descTr: "İslam hukukuna göre miras paylarını hesaplayın — Ferâiz, Asabe ve Zevil-erham",
    categoryAr: "الأدوات الإسلامية",
    categoryEn: "Islamic Tools",
    categoryTr: "İslami Araçlar",
    categorySlug: "islamic",
    schemaCategory: "Islamic",
  },
  "zakat-calculator": {
    slug: "zakat-calculator",
    nameAr: "حاسبة الزكاة",
    nameEn: "Zakat Calculator",
    nameTr: "Zekat Hesaplama",
    descAr: "احسب زكاة المال والذهب والأسهم — نصاب الزكاة ومقدارها الشرعي",
    descEn: "Calculate Zakat on money, gold, and stocks — nisab amount and Zakat due",
    descTr: "Para, altın ve hisseler için zekat hesaplayın — nisap miktarı ve zekat borcu",
    categoryAr: "الأدوات الإسلامية",
    categoryEn: "Islamic Tools",
    categoryTr: "İslami Araçlar",
    categorySlug: "islamic",
    schemaCategory: "Islamic",
  },
  "qibla-direction": {
    slug: "qibla-direction",
    nameAr: "اتجاه القبلة",
    nameEn: "Qibla Direction",
    nameTr: "Kıble Yönü",
    descAr: "اعرف اتجاه القبلة من موقعك الجغرافي — بوصلة القبلة أونلاين",
    descEn: "Find Qibla direction from your location — online Qibla compass",
    descTr: "Konumunuza göre kıble yönünü bulun — çevrimiçi kıble pusulası",
    categoryAr: "الأدوات الإسلامية",
    categoryEn: "Islamic Tools",
    categoryTr: "İslami Araçlar",
    categorySlug: "islamic",
    schemaCategory: "Islamic",
  },
  "prayer-times": {
    slug: "prayer-times",
    nameAr: "مواقيت الصلاة",
    nameEn: "Prayer Times",
    nameTr: "Namaz Vakitleri",
    descAr: "مواقيت الصلاة حسب موقعك الجغرافي — الفجر والظهر والعصر والمغرب والعشاء",
    descEn: "Prayer times by your location — Fajr, Dhuhr, Asr, Maghrib, Isha",
    descTr: "Konumunuza göre namaz vakitleri — İmsak, Öğle, İkindi, Akşam, Yatsı",
    categoryAr: "الأدوات الإسلامية",
    categoryEn: "Islamic Tools",
    categoryTr: "İslami Araçlar",
    categorySlug: "islamic",
    schemaCategory: "Islamic",
  },
  "hijri-converter": {
    slug: "hijri-converter",
    nameAr: "تحويل هجري ↔ ميلادي",
    nameEn: "Hijri ↔ Gregorian Converter",
    nameTr: "Hicri ↔ Miladi Çevirici",
    descAr: "حوّل التاريخ بين الهجري والميلادي — محوّل تاريخ دقيق مع السنة الهجرية الحالية",
    descEn: "Convert dates between Hijri and Gregorian — accurate date converter with current Hijri year",
    descTr: "Tarihleri Hicri ve Miladi arasında dönüştürün — hassas tarih çevirici",
    categoryAr: "محولات",
    categoryEn: "Converters",
    categoryTr: "Dönüştürücüler",
    categorySlug: "converters",
    schemaCategory: "Converter",
  },
  "currency-converter": {
    slug: "currency-converter",
    nameAr: "محوّل العملات",
    nameEn: "Currency Converter",
    nameTr: "Döviz Çevirici",
    descAr: "تحويل بين العملات العربية والعالمية — ريال، دولار، يورو، جنيه، درهم بأسعار لحظية",
    descEn: "Convert between Arabic and world currencies — SAR, USD, EUR, GBP, AED with live rates",
    descTr: "Arap ve dünya para birimleri arasında dönüşüm — SAR, USD, EUR, canlı kurlarla",
    categoryAr: "محولات",
    categoryEn: "Converters",
    categoryTr: "Dönüştürücüler",
    categorySlug: "converters",
    schemaCategory: "Converter",
  },
  "unit-converter": {
    slug: "unit-converter",
    nameAr: "تحويل الوحدات",
    nameEn: "Unit Converter",
    nameTr: "Birim Çevirici",
    descAr: "تحويل وحدات الطول والوزن والحجم والحرارة — جميع التحويلات في مكان واحد",
    descEn: "Convert length, weight, volume, temp — all unit conversions in one place",
    descTr: "Uzunluk, ağırlık, hacim, sıcaklık dönüşümü — tüm birim dönüşümleri tek yerde",
    categoryAr: "محولات",
    categoryEn: "Converters",
    categoryTr: "Dönüştürücüler",
    categorySlug: "converters",
    schemaCategory: "Converter",
  },
  "color-converter": {
    slug: "color-converter",
    nameAr: "محوّل الألوان",
    nameEn: "Color Converter",
    nameTr: "Renk Çevirici",
    descAr: "تحويل الألوان بين HEX و RGB و HSL — مع معاينة مباشرة للون",
    descEn: "Convert colors between HEX, RGB, and HSL — with live color preview",
    descTr: "Renkleri HEX, RGB ve HSL arasında dönüştürün — canlı renk önizlemesiyle",
    categoryAr: "محولات",
    categoryEn: "Converters",
    categoryTr: "Dönüştürücüler",
    categorySlug: "converters",
    schemaCategory: "Converter",
  },
  "word-counter": {
    slug: "word-counter",
    nameAr: "عداد الكلمات والحروف",
    nameEn: "Word & Character Counter",
    nameTr: "Kelime ve Karakter Sayacı",
    descAr: "عد الكلمات والحروف والجمل في النص — للكتابة العربية والإنجليزية",
    descEn: "Count words, characters, and sentences — for Arabic and English text",
    descTr: "Metindeki kelimeleri, karakterleri ve cümleleri sayın — Arapça ve İngilizce metinler için",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "text-case": {
    slug: "text-case",
    nameAr: "تحويل حالة النص",
    nameEn: "Text Case Converter",
    nameTr: "Metin Büyük/Küçük Harf",
    descAr: "تحويل النص لأحرف كبيرة أو صغيرة أو عنوان — Upper, Lower, Title, Sentence case",
    descEn: "Convert text to uppercase, lowercase, title case, or sentence case",
    descTr: "Metni büyük harf, küçük harf, başlık veya cümle biçimine dönüştürün",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "number-to-words": {
    slug: "number-to-words",
    nameAr: "تحويل الأرقام لحروف",
    nameEn: "Number to Words",
    nameTr: "Sayıyı Yazıya Çevirme",
    descAr: "تحويل الأرقام إلى كلمات عربية — مفيد للشيكات والمستندات المالية",
    descEn: "Convert numbers to Arabic words — useful for checks and financial documents",
    descTr: "Sayıları Türkçe yazıya dönüştürün — çekler ve finansal belgeler için kullanışlı",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "arabic-lorem": {
    slug: "arabic-lorem",
    nameAr: "مولد النص العربي",
    nameEn: "Arabic Lorem Ipsum",
    nameTr: "Arapça Lorem Ipsum",
    descAr: "توليد نص عربي وهمي للتصميم — فقرات وعنونين وقوائم للمشاريع",
    descEn: "Generate Arabic placeholder text — paragraphs, headings, and lists for design mockups",
    descTr: "Tasarımlar için Arapça yer tutucu metin oluşturun — paragraflar, başlıklar ve listeler",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "text-cleaner": {
    slug: "text-cleaner",
    nameAr: "تنظيف النص",
    nameEn: "Text Cleaner",
    nameTr: "Metin Temizleyici",
    descAr: "تنظيف النص من المسافات الزائدة والروابط والعلامات — تنظيف سريع بنقرة",
    descEn: "Clean text from extra spaces, links, and tags — fast one-click cleanup",
    descTr: "Metni fazla boşluklardan, bağlantılardan ve etiketlerden temizleyin — tek tıkla hızlı temizlik",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "text-compare": {
    slug: "text-compare",
    nameAr: "مقارنة النصوص",
    nameEn: "Text Compare",
    nameTr: "Metin Karşılaştırma",
    descAr: "قارن بين نصين واكتشف الفروقات — مقارنة فورية مع تلوين التغييرات",
    descEn: "Compare two texts and find differences — instant diff with highlighted changes",
    descTr: "İki metni karşılaştırın ve farkları bulun — vurgulanmış değişikliklerle anında karşılaştırma",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "ai-content-detector": {
    slug: "ai-content-detector",
    nameAr: "كاشف المحتوى AI",
    nameEn: "AI Content Detector",
    nameTr: "Yapay Zeka İçerik Dedektörü",
    descAr: "اكتشف إذا كان النص مكتوب بالذكاء الاصطناعي — تحليل مجاني باستخدام AI",
    descEn: "Detect if text is written by AI — free analysis powered by AI",
    descTr: "Metnin yapay zeka tarafından yazılıp yazılmadığını tespit edin — ücretsiz analiz",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "plagiarism-checker": {
    slug: "plagiarism-checker",
    nameAr: "مدقق الانتحال",
    nameEn: "Plagiarism Checker",
    nameTr: "İntihal Denetleyici",
    descAr: "كشف النصوص المنسوخة وتقييم الأصالة — فحص شامل لمقالاتك وأبحاثك",
    descEn: "Check for plagiarism and originality — comprehensive scan for articles and research",
    descTr: "Kopya metinleri tespit edin ve özgünlüğü değerlendirin — makaleler ve araştırmalar için kapsamlı tarama",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "grammar-checker": {
    slug: "grammar-checker",
    nameAr: "المدقق النحوي",
    nameEn: "Grammar Checker",
    nameTr: "Dil Bilgisi Denetleyici",
    descAr: "تدقيق الأخطاء النحوية والإملائية — باستخدام الذكاء الاصطناعي مجاناً",
    descEn: "Check grammar and spelling errors — powered by AI for free",
    descTr: "Dil bilgisi ve yazım hatalarını denetleyin — yapay zeka destekli ücretsiz araç",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "paraphrasing-tool": {
    slug: "paraphrasing-tool",
    nameAr: "إعادة الصياغة",
    nameEn: "Paraphrasing Tool",
    nameTr: "Paraphrase Aracı",
    descAr: "إعادة كتابة النص بأسلوب جديد — إعادة صياغة مجانية بالذكاء الاصطناعي",
    descEn: "Rewrite text in a new style — free AI-powered paraphrasing",
    descTr: "Metni yeni bir üslupla yeniden yazın — ücretsiz yapay zeka destekli yeniden ifade etme",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "typing-test": {
    slug: "typing-test",
    nameAr: "اختبار سرعة الكتابة",
    nameEn: "Typing Speed Test",
    nameTr: "Yazma Hızı Testi",
    descAr: "قياس سرعة طباعتك بالعربية والإنجليزية — اختبار كتابة تفاعلي",
    descEn: "Measure your typing speed in Arabic and English — interactive typing test",
    descTr: "Arapça ve İngilizce yazma hızınızı ölçün — etkileşimli yazma testi",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "social-character-counter": {
    slug: "social-character-counter",
    nameAr: "عداد حروف السوشيال",
    nameEn: "Social Media Character Counter",
    nameTr: "Sosyal Medya Karakter Sayacı",
    descAr: "عد حروف منشورات Twitter و Instagram و TikTok — لا تتجاوز المسموح",
    descEn: "Count characters for Twitter, Instagram, TikTok posts — stay within limits",
    descTr: "Twitter, Instagram, TikTok gönderileri için karakter sayın — sınırları aşmayın",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "bio-generator": {
    slug: "bio-generator",
    nameAr: "مولد السيرة الذاتية",
    nameEn: "Bio Generator",
    nameTr: "Biyografi Oluşturucu",
    descAr: "إنشاء سيرة ذاتية جذابة — لمواقع السوشيال ميديا والسيرة المهنية",
    descEn: "Create an attractive bio — for social media and professional profiles",
    descTr: "Çekici bir biyografi oluşturun — sosyal medya ve profesyonel profiller için",
    categoryAr: "أدوات نصية",
    categoryEn: "Text Tools",
    categoryTr: "Metin Araçları",
    categorySlug: "text",
    schemaCategory: "Text",
  },
  "background-remover": {
    slug: "background-remover",
    nameAr: "إزالة خلفية الصورة",
    nameEn: "Background Remover",
    nameTr: "Arka Plan Kaldırma",
    descAr: "إزالة خلفية أي صورة بالذكاء الاصطناعي — مجاني بدون تسجيل وبدون علامة مائية",
    descEn: "Remove background from any image with AI — free, no signup, no watermark",
    descTr: "Yapay zeka ile herhangi bir görselin arka planını kaldırın — ücretsiz, kayıt gerekmez, filigran yok",
    categoryAr: "أدوات الصور",
    categoryEn: "Image Tools",
    categoryTr: "Görsel Araçları",
    categorySlug: "daily",
    schemaCategory: "Image",
  },
  "image-to-text": {
    slug: "image-to-text",
    nameAr: "استخراج النص من الصور",
    nameEn: "Image to Text (OCR)",
    nameTr: "Görselden Metin (OCR)",
    descAr: "استخراج النصوص من الصور باستخدام OCR — يدعم العربية والإنجليزية مجاناً",
    descEn: "Extract text from images using OCR — supports Arabic and English for free",
    descTr: "OCR kullanarak görsellerden metin çıkarın — Arapça ve İngilizce desteği ücretsiz",
    categoryAr: "أدوات الصور",
    categoryEn: "Image Tools",
    categoryTr: "Görsel Araçları",
    categorySlug: "daily",
    schemaCategory: "Image",
  },
  "image-resizer": {
    slug: "image-resizer",
    nameAr: "تغيير حجم الصور",
    nameEn: "Image Resizer",
    nameTr: "Görsel Boyutlandırma",
    descAr: "تغيير أبعاد الصور مجاناً — تصغير أو تكبير دون فقدان الجودة",
    descEn: "Resize images for free — scale up or down without quality loss",
    descTr: "Görselleri ücretsiz yeniden boyutlandırın — kalite kaybı olmadan büyütün veya küçültün",
    categoryAr: "أدوات الصور",
    categoryEn: "Image Tools",
    categoryTr: "Görsel Araçları",
    categorySlug: "daily",
    schemaCategory: "Image",
  },
  "image-compressor": {
    slug: "image-compressor",
    nameAr: "ضغط الصور",
    nameEn: "Image Compressor",
    nameTr: "Görsel Sıkıştırma",
    descAr: "تقليل حجم ملفات الصور — ضغط JPG و PNG مع الحفاظ على الجودة",
    descEn: "Reduce image file size — compress JPG and PNG while maintaining quality",
    descTr: "Görsel dosya boyutunu azaltın — kaliteyi koruyarak JPG ve PNG sıkıştırma",
    categoryAr: "أدوات الصور",
    categoryEn: "Image Tools",
    categoryTr: "Görsel Araçları",
    categorySlug: "daily",
    schemaCategory: "Image",
  },
  "image-to-pdf": {
    slug: "image-to-pdf",
    nameAr: "صورة إلى PDF",
    nameEn: "Image to PDF",
    nameTr: "Görselden PDF'e",
    descAr: "تحويل الصور إلى ملف PDF — تحويل سريع مع دعم عدة صور في ملف واحد",
    descEn: "Convert images to PDF — fast conversion with support for multiple images",
    descTr: "Görselleri PDF'e dönüştürün — birden çok görseli tek dosyada destekler",
    categoryAr: "أدوات PDF",
    categoryEn: "PDF Tools",
    categoryTr: "PDF Araçları",
    categorySlug: "daily",
    schemaCategory: "PDF",
  },
  "youtube-thumbnail-downloader": {
    slug: "youtube-thumbnail-downloader",
    nameAr: "تحميل ثامبنيل يوتيوب",
    nameEn: "YouTube Thumbnail Downloader",
    nameTr: "YouTube Küçük Resim İndirici",
    descAr: "تحميل صور مصغرة ليوتيوب بجودة عالية — HD و 4K مجاناً",
    descEn: "Download YouTube thumbnails in HD and 4K — free, no signup",
    descTr: "YouTube küçük resimlerini HD ve 4K kalitesinde indirin — ücretsiz, kayıt gerekmez",
    categoryAr: "أدوات الصور",
    categoryEn: "Image Tools",
    categoryTr: "Görsel Araçları",
    categorySlug: "daily",
    schemaCategory: "Image",
  },
  "pdf-merger": {
    slug: "pdf-merger",
    nameAr: "دمج ملفات PDF",
    nameEn: "PDF Merger",
    nameTr: "PDF Birleştirme",
    descAr: "دمج عدة ملفات PDF في ملف واحد — مجاني وسريع بدون علامة مائية",
    descEn: "Merge multiple PDF files into one — free and fast with no watermark",
    descTr: "Birden çok PDF dosyasını tek bir dosyada birleştirin — ücretsiz, hızlı, filigransız",
    categoryAr: "أدوات PDF",
    categoryEn: "PDF Tools",
    categoryTr: "PDF Araçları",
    categorySlug: "daily",
    schemaCategory: "PDF",
  },
  "pdf-splitter": {
    slug: "pdf-splitter",
    nameAr: "تقسيم ملفات PDF",
    nameEn: "PDF Splitter",
    nameTr: "PDF Ayırma",
    descAr: "تقسيم PDF إلى صفحات منفصلة — استخراج صفحات محددة أو تقسيم كل صفحة",
    descEn: "Split PDF into separate pages — extract specific pages or split every page",
    descTr: "PDF'i ayrı sayfalara bölün — belirli sayfaları çıkarın veya her sayfayı ayırın",
    categoryAr: "أدوات PDF",
    categoryEn: "PDF Tools",
    categoryTr: "PDF Araçları",
    categorySlug: "daily",
    schemaCategory: "PDF",
  },
  "pdf-compressor": {
    slug: "pdf-compressor",
    nameAr: "ضغط ملفات PDF",
    nameEn: "PDF Compressor",
    nameTr: "PDF Sıkıştırma",
    descAr: "تقليل حجم ملفات PDF — ضغط ذكي مع الحفاظ على الجودة",
    descEn: "Reduce PDF file size — smart compression while maintaining quality",
    descTr: "PDF dosya boyutunu azaltın — kaliteyi korurken akıllı sıkıştırma",
    categoryAr: "أدوات PDF",
    categoryEn: "PDF Tools",
    categoryTr: "PDF Araçları",
    categorySlug: "daily",
    schemaCategory: "PDF",
  },
  "pdf-to-word": {
    slug: "pdf-to-word",
    nameAr: "PDF إلى Word",
    nameEn: "PDF to Word",
    nameTr: "PDF'den Word'e",
    descAr: "تحويل ملفات PDF إلى نصوص Word قابلة للتعديل — محلي بدون رفع ملفات",
    descEn: "Convert PDF to editable Word text — local processing, no file upload needed",
    descTr: "PDF'i düzenlenebilir Word metnine dönüştürün — yerel işlem, dosya yükleme gerektirmez",
    categoryAr: "أدوات PDF",
    categoryEn: "PDF Tools",
    categoryTr: "PDF Araçları",
    categorySlug: "daily",
    schemaCategory: "PDF",
  },
  "qr-generator": {
    slug: "qr-generator",
    nameAr: "مولد QR Code",
    nameEn: "QR Code Generator",
    nameTr: "QR Kod Oluşturucu",
    descAr: "إنشاء QR Code لأي رابط أو نص — توليد فوري مع تحميل PNG",
    descEn: "Generate QR Code for any link or text — instant generation with PNG download",
    descTr: "Herhangi bir bağlantı veya metin için QR kodu oluşturun — anında oluşturma ve PNG indirme",
    categoryAr: "مولدات",
    categoryEn: "Generators",
    categoryTr: "Oluşturucular",
    categorySlug: "generators",
    schemaCategory: "Generator",
  },
  "qr-reader": {
    slug: "qr-reader",
    nameAr: "قارئ QR Code",
    nameEn: "QR Code Reader",
    nameTr: "QR Kod Okuyucu",
    descAr: "قراءة رموز QR من الصور أو الكاميرا — قارئ سريع ودقيق",
    descEn: "Read QR codes from images or camera — fast and accurate reader",
    descTr: "Görsellerden veya kameradan QR kodları okuyun — hızlı ve doğru okuyucu",
    categoryAr: "مولدات",
    categoryEn: "Generators",
    categoryTr: "Oluşturucular",
    categorySlug: "generators",
    schemaCategory: "Generator",
  },
  "barcode-generator": {
    slug: "barcode-generator",
    nameAr: "مولد الباركود",
    nameEn: "Barcode Generator",
    nameTr: "Barkod Oluşturucu",
    descAr: "إنشاء باركود احترافي — 8 أنواع مختلفة للمنتجات والمخازن",
    descEn: "Generate professional barcodes — 8 different types for products and warehouses",
    descTr: "Profesyonel barkodlar oluşturun — ürünler ve depolar için 8 farklı tür",
    categoryAr: "مولدات",
    categoryEn: "Generators",
    categoryTr: "Oluşturucular",
    categorySlug: "generators",
    schemaCategory: "Generator",
  },
  "password-generator": {
    slug: "password-generator",
    nameAr: "مولد كلمات السر",
    nameEn: "Password Generator",
    nameTr: "Şifre Oluşturucu",
    descAr: "توليد كلمات سر قوية وآمنة — قابلة للتخصيص بطول ونوع الحروف",
    descEn: "Generate strong, secure passwords — customizable by length and character types",
    descTr: "Güçlü, güvenli şifreler oluşturun — uzunluk ve karakter türüne göre özelleştirilebilir",
    categoryAr: "مولدات",
    categoryEn: "Generators",
    categoryTr: "Oluşturucular",
    categorySlug: "generators",
    schemaCategory: "Generator",
  },
  "invoice-generator": {
    slug: "invoice-generator",
    nameAr: "مولد الفواتير",
    nameEn: "Invoice Generator",
    nameTr: "Fatura Oluşturucu",
    descAr: "إنشاء فاتورة احترافية — فواتير بصيغة PDF جاهزة للطباعة",
    descEn: "Create professional invoices — PDF invoices ready to print",
    descTr: "Profesyonel faturalar oluşturun — yazdırılmaya hazır PDF faturalar",
    categoryAr: "مولدات",
    categoryEn: "Generators",
    categoryTr: "Oluşturucular",
    categorySlug: "generators",
    schemaCategory: "Generator",
  },
  "whatsapp-link": {
    slug: "whatsapp-link",
    nameAr: "رابط واتساب مباشر",
    nameEn: "WhatsApp Link Generator",
    nameTr: "WhatsApp Bağlantı Oluşturucu",
    descAr: "إنشاء رابط يفتح واتساب مباشرة — مع رسالة مسبقة ورقم الهاتف",
    descEn: "Generate a direct WhatsApp link — with pre-filled message and phone number",
    descTr: "Doğrudan WhatsApp bağlantısı oluşturun — önceden doldurulmuş mesaj ve telefon numarasıyla",
    categoryAr: "مولدات",
    categoryEn: "Generators",
    categoryTr: "Oluşturucular",
    categorySlug: "generators",
    schemaCategory: "Generator",
  },
  "random-number": {
    slug: "random-number",
    nameAr: "مولد أرقام عشوائية",
    nameEn: "Random Number Generator",
    nameTr: "Rastgele Sayı Oluşturucu",
    descAr: "توليد أرقام عشوائية بين نطاق محدد — سريع ومجاني",
    descEn: "Generate random numbers within a specified range — fast and free",
    descTr: "Belirtilen aralıkta rastgele sayılar oluşturun — hızlı ve ücretsiz",
    categoryAr: "مولدات",
    categoryEn: "Generators",
    categoryTr: "Oluşturucular",
    categorySlug: "generators",
    schemaCategory: "Generator",
  },
  "name-generator": {
    slug: "name-generator",
    nameAr: "مولد أسماء",
    nameEn: "Name Generator",
    nameTr: "İsim Oluşturucu",
    descAr: "توليد أسماء عربية وإنجليزية — للمشاريع والشخصيات والألعاب",
    descEn: "Generate Arabic and English names — for projects, characters, and games",
    descTr: "Arapça ve İngilizce isimler oluşturun — projeler, karakterler ve oyunlar için",
    categoryAr: "مولدات",
    categoryEn: "Generators",
    categoryTr: "Oluşturucular",
    categorySlug: "generators",
    schemaCategory: "Generator",
  },
  "json-formatter": {
    slug: "json-formatter",
    nameAr: "JSON Formatter",
    nameEn: "JSON Formatter",
    nameTr: "JSON Biçimlendirici",
    descAr: "تنسيق وتجميل والتحقق من أكواد JSON — مع تلوين الأكواد",
    descEn: "Format, beautify, and validate JSON code — with syntax highlighting",
    descTr: "JSON kodlarını biçimlendirin, güzelleştirin ve doğrulayın — sözdizimi vurgulamalı",
    categoryAr: "تطوير ويب",
    categoryEn: "Dev Tools",
    categoryTr: "Geliştirici Araçları",
    categorySlug: "dev",
    schemaCategory: "Development",
  },
  "base64-encoder": {
    slug: "base64-encoder",
    nameAr: "Base64 Encoder",
    nameEn: "Base64 Encoder/Decoder",
    nameTr: "Base64 Kodlayıcı/Kod Çözücü",
    descAr: "تشفير وفك تشفير Base64 — للنصوص والصور",
    descEn: "Encode and decode Base64 — for text and images",
    descTr: "Metin ve görseller için Base64 kodlama ve kod çözme",
    categoryAr: "تطوير ويب",
    categoryEn: "Dev Tools",
    categoryTr: "Geliştirici Araçları",
    categorySlug: "dev",
    schemaCategory: "Development",
  },
  "hash-generator": {
    slug: "hash-generator",
    nameAr: "Hash Generator",
    nameEn: "Hash Generator",
    nameTr: "Hash Oluşturucu",
    descAr: "توليد هاشات MD5 و SHA-1 و SHA-256 و SHA-512 — للتحقق من سلامة الملفات",
    descEn: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes — for file integrity verification",
    descTr: "MD5, SHA-1, SHA-256, SHA-512 hash'leri oluşturun — dosya bütünlüğü doğrulama için",
    categoryAr: "تطوير ويب",
    categoryEn: "Dev Tools",
    categoryTr: "Geliştirici Araçları",
    categorySlug: "dev",
    schemaCategory: "Development",
  },
  "seo-audit": {
    slug: "seo-audit",
    nameAr: "SEO Audit",
    nameEn: "SEO Audit Tool",
    nameTr: "SEO Denetim Aracı",
    descAr: "تدقيق وتحليل السيو لأي موقع — تقرير شامل مع نقاط القوة والضعف والتوصيات",
    descEn: "Audit and analyze any website's SEO — comprehensive report with strengths, weaknesses, and recommendations",
    descTr: "Herhangi bir web sitesinin SEO'sunu denetleyin ve analiz edin — kapsamlı rapor",
    categoryAr: "تطوير ويب",
    categoryEn: "Dev Tools",
    categoryTr: "Geliştirici Araçları",
    categorySlug: "dev",
    schemaCategory: "Development",
  },
  "css-minifier": {
    slug: "css-minifier",
    nameAr: "تصغير CSS",
    nameEn: "CSS Minifier",
    nameTr: "CSS Küçültücü",
    descAr: "تصغير وتنسيق أكواد CSS — Minify و Format بنقرة واحدة",
    descEn: "Minify and format CSS code — compress or beautify with one click",
    descTr: "CSS kodlarını küçültün ve biçimlendirin — tek tıkla sıkıştırın veya güzelleştirin",
    categoryAr: "تطوير ويب",
    categoryEn: "Dev Tools",
    categoryTr: "Geliştirici Araçları",
    categorySlug: "dev",
    schemaCategory: "Development",
  },
  "markdown-editor": {
    slug: "markdown-editor",
    nameAr: "محرر ماركداون",
    nameEn: "Markdown Editor",
    nameTr: "Markdown Düzenleyici",
    descAr: "كتابة Markdown مع معاينة مباشرة — محرر فوري بالعربي والإنجليزي",
    descEn: "Write Markdown with live preview — instant editor in Arabic and English",
    descTr: "Markdown'ı canlı önizlemeyle yazın — Arapça ve İngilizce anlık düzenleyici",
    categoryAr: "تطوير ويب",
    categoryEn: "Dev Tools",
    categoryTr: "Geliştirici Araçları",
    categorySlug: "dev",
    schemaCategory: "Development",
  },
  "ip-lookup": {
    slug: "ip-lookup",
    nameAr: "البحث عن IP",
    nameEn: "IP Lookup",
    nameTr: "IP Sorgulama",
    descAr: "الكشف عن معلومات أي عنوان IP — الموقع الجغرافي ومزود الخدمة",
    descEn: "Look up any IP address info — geographic location and ISP",
    descTr: "Herhangi bir IP adresinin bilgilerini görüntüleyin — coğrafi konum ve ISS",
    categoryAr: "تطوير ويب",
    categoryEn: "Dev Tools",
    categoryTr: "Geliştirici Araçları",
    categorySlug: "dev",
    schemaCategory: "Development",
  },
  "encoder": {
    slug: "encoder",
    nameAr: "أداة الترميز",
    nameEn: "URL Encoder/Decoder",
    nameTr: "URL Kodlayıcı/Kod Çözücü",
    descAr: "تشفير وفك تشفير الروابط — URL Encode و Decode فوري",
    descEn: "Encode and decode URLs — instant URL encoding and decoding",
    descTr: "URL'leri kodlayın ve kodunu çözün — anında URL kodlama ve kod çözme",
    categoryAr: "تطوير ويب",
    categoryEn: "Dev Tools",
    categoryTr: "Geliştirici Araçları",
    categorySlug: "dev",
    schemaCategory: "Development",
  },
  "age-calculator": {
    slug: "age-calculator",
    nameAr: "حاسبة العمر",
    nameEn: "Age Calculator",
    nameTr: "Yaş Hesaplama",
    descAr: "احسب عمرك بالهجري والميلادي — عمرك بالسنوات والأشهر والأيام وأبراجك",
    descEn: "Calculate your age in Hijri and Gregorian — years, months, days, and your zodiac sign",
    descTr: "Hicri ve Miladi olarak yaşınızı hesaplayın — yıl, ay, gün ve burcunuz",
    categoryAr: "أدوات أخرى",
    categoryEn: "Other Tools",
    categoryTr: "Diğer Araçlar",
    categorySlug: "daily",
    schemaCategory: "Utility",
  },
  "bmi-calculator": {
    slug: "bmi-calculator",
    nameAr: "حاسبة BMI",
    nameEn: "BMI Calculator",
    nameTr: "VKİ Hesaplama",
    descAr: "احسب مؤشر كتلة الجسم (BMI) — مع دليل التصنيفات الصحية حسب منظمة الصحة العالمية",
    descEn: "Calculate Body Mass Index (BMI) — with WHO health category guidelines",
    descTr: "Vücut Kitle İndeksinizi (VKİ) hesaplayın — WHO sağlık kategorisi kılavuzuyla",
    categoryAr: "أدوات أخرى",
    categoryEn: "Other Tools",
    categoryTr: "Diğer Araçlar",
    categorySlug: "daily",
    schemaCategory: "Health",
  },
  "calorie-calculator": {
    slug: "calorie-calculator",
    nameAr: "حاسبة السعرات",
    nameEn: "Calorie Calculator",
    nameTr: "Kalori Hesaplama",
    descAr: "احسب السعرات الحرارية اليومية — للتخفيف أو زيادة الوزن أو الحفاظ عليه",
    descEn: "Calculate daily calorie needs — for weight loss, gain, or maintenance",
    descTr: "Günlük kalori ihtiyacınızı hesaplayın — kilo verme, alma veya koruma için",
    categoryAr: "أدوات أخرى",
    categoryEn: "Other Tools",
    categoryTr: "Diğer Araçlar",
    categorySlug: "daily",
    schemaCategory: "Health",
  },
  "stopwatch": {
    slug: "stopwatch",
    nameAr: "ساعة إيقاف",
    nameEn: "Stopwatch",
    nameTr: "Kronometre",
    descAr: "ساعة إيقاف مع لفات ومؤقت — ساعة إيقاف أونلاين دقيقة",
    descEn: "Stopwatch with lap timer — precise online stopwatch",
    descTr: "Kronometre ve zamanlayıcı — hassas çevrimiçi kronometre",
    categoryAr: "أدوات أخرى",
    categoryEn: "Other Tools",
    categoryTr: "Diğer Araçlar",
    categorySlug: "daily",
    schemaCategory: "Utility",
  },
  "seo-content-generator": {
    slug: "seo-content-generator",
    nameAr: "مولد محتوى SEO",
    nameEn: "SEO Content Generator",
    nameTr: "SEO İçerik Oluşturucu",
    descAr: "توليد محتوى محسّن لمحركات البحث — باستخدام الذكاء الاصطناعي",
    descEn: "Generate SEO-optimized content — powered by AI",
    descTr: "Arama motorları için optimize edilmiş içerik oluşturun — yapay zeka destekli",
    categoryAr: "تطوير ويب",
    categoryEn: "Dev Tools",
    categoryTr: "Geliştirici Araçları",
    categorySlug: "dev",
    schemaCategory: "Development",
  },
};

/**
 * Generate Next.js Metadata for a tool page
 */
export function generateToolMetadata(slug: string, lang: "ar" | "en" | "tr" = "ar") {
  const tool = TOOLS_META[slug];
  if (!tool) return null;

  const name = lang === "ar" ? tool.nameAr : lang === "tr" ? tool.nameTr : tool.nameEn;
  const desc = lang === "ar" ? tool.descAr : lang === "tr" ? tool.descTr : tool.descEn;
  // Don't append site name — root layout template adds "%s — أدواتك" automatically
  const title = name;
  const canonical = lang === "ar"
    ? `https://adwatak.cloud/tools/${slug}`
    : lang === "tr"
    ? `https://adwatak.cloud/tr/tools/${slug}`
    : `https://adwatak.cloud/en/tools/${slug}`;

  return {
    title,
    description: desc.substring(0, 160),
    alternates: {
      canonical,
      languages: {
        "ar": `https://adwatak.cloud/tools/${slug}`,
        "en": `https://adwatak.cloud/en/tools/${slug}`,
        "tr": `https://adwatak.cloud/tr/tools/${slug}`,
      },
    },
    openGraph: {
      title,
      description: desc.substring(0, 200),
      url: canonical,
      siteName: lang === "ar" ? "أدواتك" : lang === "tr" ? "Adwatak" : "Adawatak",
      locale: lang === "ar" ? "ar_SA" : lang === "tr" ? "tr_TR" : "en_US",
      type: "website" as const,
      images: [
        {
          url: lang === "ar"
            ? `https://adwatak.cloud/og/${slug}`
            : lang === "tr"
            ? `https://adwatak.cloud/tr/og/${slug}`
            : `https://adwatak.cloud/en/og/${slug}`,
          width: 1200,
          height: 630,
          alt: name,
        },
      ],
    },
    twitter: {
      card: "summary_large_image" as const,
      title,
      description: desc.substring(0, 200),
      images: [
        lang === "ar"
          ? `https://adwatak.cloud/og/${slug}`
          : lang === "tr"
          ? `https://adwatak.cloud/tr/og/${slug}`
          : `https://adwatak.cloud/en/og/${slug}`,
      ],
    },
  };
}

/**
 * Generate breadcrumb schema data (JSON-LD) for a tool
 */
export function generateBreadcrumbSchema(slug: string, lang: "ar" | "en" | "tr" = "ar") {
  const tool = TOOLS_META[slug];
  if (!tool) return null;

  const name = lang === "ar" ? tool.nameAr : lang === "tr" ? tool.nameTr : tool.nameEn;
  const category = lang === "ar" ? tool.categoryAr : lang === "tr" ? tool.categoryTr : tool.categoryEn;
  const homeText = lang === "ar" ? "الرئيسية" : lang === "tr" ? "Ana Sayfa" : "Home";
  const prefix = lang === "ar" ? "" : lang === "tr" ? "/tr" : "/en";
  const toolUrl = lang === "ar"
    ? `https://adwatak.cloud/tools/${slug}`
    : lang === "tr"
    ? `https://adwatak.cloud/tr/tools/${slug}`
    : `https://adwatak.cloud/en/tools/${slug}`;

  return [
    { name: homeText, url: `https://adwatak.cloud${prefix}` },
    { name: category, url: `https://adwatak.cloud${prefix}/category/${tool.categorySlug}` },
    { name: name, url: toolUrl },
  ];
}

/**
 * Get tool info for use in client components (breadcrumb, etc.)
 */
export function getToolInfo(slug: string, lang: "ar" | "en" | "tr" = "ar") {
  const tool = TOOLS_META[slug];
  if (!tool) return null;

  return {
    name: lang === "ar" ? tool.nameAr : lang === "tr" ? tool.nameTr : tool.nameEn,
    description: lang === "ar" ? tool.descAr : lang === "tr" ? tool.descTr : tool.descEn,
    category: lang === "ar" ? tool.categoryAr : lang === "tr" ? tool.categoryTr : tool.categoryEn,
    categorySlug: tool.categorySlug,
    schemaCategory: tool.schemaCategory,
  };
}

/**
 * AEO: Get direct answer summary for AI engines.
 * Concise 1-2 sentence answer AI engines can quote directly.
 */
export function getToolDirectAnswer(slug: string, lang: "ar" | "en" | "tr" = "ar"): string {
  const tool = TOOLS_META[slug];
  if (!tool) return "";

  if (lang === "ar") {
    return `${tool.nameAr} — ${tool.descAr}`;
  } else if (lang === "tr") {
    return `${tool.nameTr} — ${tool.descTr}`;
  }
  return `${tool.nameEn} — ${tool.descEn}`;
}

/**
 * GEO: Speakable specification for tool pages.
 */
export function getToolSpeakableData(): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": "SpeakableSpecification",
    cssSelector: [".tool-description", ".faq-answer", "h1", "h2", ".seo-content"],
  };
}

/**
 * GEO: Get keywords for long-tail targeting.
 */
export function getToolKeywords(slug: string, lang: "ar" | "en" | "tr" = "ar"): string[] {
  const tool = TOOLS_META[slug];
  if (!tool) return [];

  const name = lang === "ar" ? tool.nameAr : lang === "tr" ? tool.nameTr : tool.nameEn;
  const category = lang === "ar" ? tool.categoryAr : lang === "tr" ? tool.categoryTr : tool.categoryEn;

  if (lang === "ar") {
    return [name, category, `${name} مجاني`, `استخدام ${name}`, `كيف ${name}`];
  }
  if (lang === "tr") {
    return [name, category, `${name} ücretsiz`, `nasıl ${name} kullanılır`];
  }
  return [name, category, `free ${name}`, `how to use ${name}`, `${name} online`];
}
